### ISSUE TITLE
Relocated snakeyaml package not correct in META-INF/versions

### ISSUE THREAD

**Issue by schmist** [datafaker-net/datafaker#1007]
**Describe the bug**
The relocated snakeyaml package is not correctly transformed for a multi-release jar setup. The package path is still `META-INF/versions/9/org/yaml/snakeyaml/internal`  but the  `Logger.class` valid for Java version 9 and higher (inside this folder) uses `package net.datafaker.shaded.snakeyaml.internal` as package name. This is probably caused by the Maven shaded plugin but you might have a workaround to fix it. The not correctly shaded path leads to collisions with not shaded snakeyaml variants when executing multi-release jars.

**To Reproduce**
Open (unpack) the datafaker jar and find the `META-INF/versions/9` folder and the snakeyaml package.

**Expected behavior**
The multi-release variant package path shoud be correctly shaded `META-INF/versions/9/net/datafaker/shaded/snakeyaml/internal`

**Versions:**
 - JRE >= 9
 - Faker Version 2.0.2

**Comment by bodiam** [comment]
Hi Stefan, thanks for your report. Forgive my ignorance, but what is a multi release jar? 

How does this issue affect you in practice, and how can we reproduce this? If you have any insights on how to fix, or a PR, that would be most welcome.

**Comment by schmist** [comment]
Multi-release jar: For details see https://openjdk.org/jeps/238. Essentially it is a mechanism to allow JDK version dependent implementation of the same functionality, e.g., to use newly added Java API for an improved implementation, in a single jar.

The problem is caused by a bug in the Maven Shade plugin, see https://issues.apache.org/jira/browse/MSHADE-406.

When building a fat jar, the shaded but not relocated package path conflicts with the real snakeyaml path (for the multi-release classes). In our case the relocated version from datafaker wins and overwrites the correct one, which leads to class not found problems during runtime (caused by the fact that the package name inside the class file was rewritten to the shaded package name).

I created a pull request which should fix the problem.
