### ISSUE TITLE
Language code provider

### ISSUE THREAD

**Issue by u1925** [datafaker-net/datafaker#1017]
**Suggestion**

I'd like to have a provider that gives me a random 2-letter ISO 639 language code based upon [Java ISO language codes](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Locale.html#getISOLanguages()).

Will submit a PR for this... soon.

**Comment by kingthorin** [comment]
```java
List<String> langs = getISOLanguages();
getISOLanguages().get(rand.nextInt(langs.size()));
```

**Comment by u1925** [comment]
PR submitted, quite a small one!
