### ISSUE TITLE
Add Muslim Names Feature Request

### ISSUE THREAD

**Issue by zahikhan** [datafaker-net/datafaker#1046]
Hi Team,

I am working on a Project where I am interested in the Muslim names only like Muslim first name, last name etc. 

It would be great if we could fake names based on the religion only.

```
        Faker faker = new Faker();

        String name = faker.name().muslim().fullName(); // Miss Ayman Khan
        String firstName = faker.name().muslim().firstName(); // Maryam
        String lastName = faker.name().muslim().lastName(); // Ibrahim
```

**Comment by bodiam** [comment]
Have you looked into creating your own custom faker? This looks like a great usecase for that.

https://www.datafaker.net/documentation/custom-providers/

**Comment by zahikhan** [comment]
Hi @bodiam 
The said `custom-providers` can be worked around for me, and I can make it work. However, I want to make a contribution to the library regarding the same.

**Comment by bodiam** [comment]
No problem, PRs always welcome. Feel free to send one!
