### ISSUE TITLE
Lorem words are not unique

### ISSUE THREAD

**Issue by TamasSzigeti** [datafaker-net/datafaker#1064]
**Describe the bug**

There are several repeated words in `lorem.words` and `lorem.supplemental`, and given the unique provider doesn't check values but works with index, it returns the same value multiple times.

I can submit a PR just wanted to check in if there is any reason for the duplicates.
This can be solved by either removing duplicates or improving the unique provider to not return duplicates even if the yaml contains them. This latter approach is a bit more work but safer, more robust.

**To Reproduce**

```
faker.unique().fetchFromYaml("lorem.words")
faker.unique().fetchFromYaml("lorem.supplemental")
```

**Expected behavior**

Unique values are returned.

**Versions:**
 - Faker Version 2.1.0

**Comment by kingthorin** [comment]
Are they expected to be unique? I'm pretty sure it's a finite collection.

**Comment by kingthorin** [comment]
I'll do some testing.

**Comment by kingthorin** [comment]
Okay I see the issue, there is indeed 75 dupes in the word list 😞

**Comment by kingthorin** [comment]
Words:
249 currently
182 de-duped

<details>
<summary>De-duped list</summary>

```yml
-"alias"
-"consequatur"
-"aut"
-"perferendis"
-"sit"
-"voluptatem"
-"accusantium"
-"doloremque"
-"aperiam"
-"eaque"
-"ipsa"
-"quae"
-"ab"
-"illo"
-"inventore"
-"veritatis"
-"et"
-"quasi"
-"architecto"
-"beatae"
-"vitae"
-"dicta"
-"sunt"
-"explicabo"
-"aspernatur"
-"odit"
-"fugit"
-"sed"
-"quia"
-"consequuntur"
-"magni"
-"dolores"
-"eos"
-"qui"
-"ratione"
-"sequi"
-"nesciunt"
-"neque"
-"dolorem"
-"ipsum"
-"dolor"
-"amet"
-"consectetur"
-"adipisci"
-"velit"
-"non"
-"numquam"
-"eius"
-"modi"
-"tempora"
-"incidunt"
-"ut"
-"labore"
-"dolore"
-"magnam"
-"aliquam"
-"quaerat"
-"enim"
-"ad"
-"minima"
-"veniam"
-"quis"
-"nostrum"
-"exercitationem"
-"ullam"
-"corporis"
-"nemo"
-"ipsam"
-"voluptas"
-"suscipit"
-"laboriosam"
-"nisi"
-"aliquid"
-"ex"
-"ea"
-"commodi"
-"autem"
-"vel"
-"eum"
-"iure"
-"reprehenderit"
-"in"
-"voluptate"
-"esse"
-"quam"
-"nihil"
-"molestiae"
-"iusto"
-"odio"
-"dignissimos"
-"ducimus"
-"blanditiis"
-"praesentium"
-"laudantium"
-"totam"
-"rem"
-"voluptatum"
-"deleniti"
-"atque"
-"corrupti"
-"quos"
-"quas"
-"molestias"
-"excepturi"
-"sint"
-"occaecati"
-"cupiditate"
-"provident"
-"perspiciatis"
-"unde"
-"omnis"
-"iste"
-"natus"
-"error"
-"similique"
-"culpa"
-"officia"
-"deserunt"
-"mollitia"
-"animi"
-"id"
-"est"
-"laborum"
-"dolorum"
-"fuga"
-"harum"
-"quidem"
-"rerum"
-"facilis"
-"expedita"
-"distinctio"
-"nam"
-"libero"
-"tempore"
-"cum"
-"soluta"
-"nobis"
-"eligendi"
-"optio"
-"cumque"
-"impedit"
-"quo"
-"porro"
-"quisquam"
-"minus"
-"quod"
-"maxime"
-"placeat"
-"facere"
-"possimus"
-"assumenda"
-"repellendus"
-"temporibus"
-"quibusdam"
-"illum"
-"fugiat"
-"nulla"
-"pariatur"
-"at"
-"vero"
-"accusamus"
-"officiis"
-"debitis"
-"necessitatibus"
-"saepe"
-"eveniet"
-"voluptates"
-"repudiandae"
-"recusandae"
-"itaque"
-"earum"
-"hic"
-"tenetur"
-"a"
-"sapiente"
-"delectus"
-"reiciendis"
-"voluptatibus"
-"maiores"
-"doloribus"
-"asperiores"
-"repellat"
```

</details>

Supplemental 840 currently, does not seem to have any duplicates.

**Comment by TamasSzigeti** [comment]
There are a few cross-duplications too: words in supplemental that are also in words

**Comment by kingthorin** [comment]
I was able to identify 8 that overlap between the two lists does that sound right? I propose these are removed from supplemental, do you agree that makes the most sense?

**Comment by TamasSzigeti** [comment]
Yes I also counted 8 and do agree that they should be removed. Shall I submit a PR or you are already on it?

**Comment by kingthorin** [comment]
If you e got time/interest please go for it. I e just been manipulating lists in notepad++ and Excel 🙂
