### ISSUE TITLE
Fake schema generating always the same name

### ISSUE THREAD

**Issue by fmarchioni** [datafaker-net/datafaker#1070]
I'd like to use the Schema generation (and transformation) as part of my Unit Testing. However, it appears that data produced through a schema (requesting a single item) always returns the same result.

**To Reproduce**

```
import net.datafaker.providers.base.BaseFaker;
import net.datafaker.transformations.JsonTransformer;
import net.datafaker.transformations.Schema;
import static net.datafaker.transformations.Field.field;


import java.util.Random;
public class MethodMatch {

    public static void main(String[] args) {
        BaseFaker faker = new BaseFaker(new Random(100L));
        Schema<Object, ?> schema = Schema.of(
            field("Text", () -> faker.name().firstName()),
            field("Bool", () -> faker.bool().bool())
        );

        JsonTransformer<Object> transformer = JsonTransformer.builder().build();
        String json = transformer.generate(schema, 1);
 
        System.out.println(json);
       
    }
 

 
}
```

 
The result for every execution is:

`{"Text": "Dion", "Bool": false}`

Is it possible to have different (random) data when requesting a single item:

` String json = transformer.generate(schema, 1);`

I'm using version 1.9.0

Thanks

**Comment by kingthorin** [comment]
If your random seed is static wouldn't that be expected? (Note I haven't tested or played with this functionality, so I'm kinda guessing but that stands out.)

**Comment by snuyanzin** [comment]
That's the idea of repeatability feature: if something is invoked for thesame seed in your case `new Random(100L)` after same steps the result will be same.

If you want to have different result each time and do not case about repeatability then just use `ThreadLocalRandom.current()` like 
```java
    public static void main(String[] args) {
        BaseFaker faker = new BaseFaker(ThreadLocalRandom.current());
        Schema<Object, ?> schema = Schema.of(
            field("Text", () -> faker.name().firstName()),
            field("Bool", () -> faker.bool().bool())
        );

        JsonTransformer<Object> transformer = JsonTransformer.builder().build();
        String json = transformer.generate(schema, 1);

        System.out.println(json);
    }
```

**Comment by fmarchioni** [comment]
Thanks for your feedback! Indeed I was just replying that I'm unable to change the seed as in the real example I'm attaching a static schema to my Java Beans. With your suggestion it works perfectly thanks!

```
public class CustomerSchema {
      public static Schema<Object, ?> defaultSchema() {
         var faker = new Faker(Locale.getDefault(), ThreadLocalRandom.current());
            return Schema.of(
            field("name", () -> faker.name().firstName()),
            field("surname", () -> faker.name().lastName())
            );
     }
    
}

@FakeForSchema("com.sample.model.CustomerSchema#defaultSchema") 
public class Customer {
}
```
