### ISSUE TITLE
Diffierent value if recall values

### ISSUE THREAD

**Issue by Kieaer** [datafaker-net/datafaker#1075]
**Describe the bug**
Same title

**To Reproduce**
```java
Faker faker = new Faker();
for (int i = 0; i < 10; i++) {
    System.out.println(faker.company().name());
}
```

```java
Faker faker = new Faker(new Random(0));
for (int i = 0; i < 10; i++) {
    System.out.println(faker.company().name());
}
```

**Expected behavior**
Print same values

**Versions:**
 - OS: Windows 11
 - JDK 17
 - Faker Version 2.1.0

**Additional context**
None.

**Comment by kingthorin** [comment]
If you want consistent value you have to provide a consistent seed. 

By default and design data faker is made to generate data, not consistent data. Hence providing the option for users to provide a consistent seed and get consistent data.

**Comment by bodiam** [comment]
I'm not sure what you mean with "print same values", but the second example should print the same output on every run. The first one won't, since you create a faker with a random seed. Please provide more info if you think this is still an issue.
