### ISSUE TITLE
aws().vpcId() generates invalid id

### ISSUE THREAD

**Issue by axelfontaine** [datafaker-net/datafaker#1076]
**Describe the bug**
`aws().vpcId()` generates invalid id such as `vpc-8e6792c23ea07abf`

**To Reproduce**
`faker.aws().vpcId()`

**Expected behavior**
valid vpc id such as `vpc-08e6792c23ea07abf` (note the extra `0` !)

**Versions:**
 - OS: Win11 x64
 - JDK 21
 - Faker Version 2.0.

**Additional context**
same issue with `subnetId()` and `securityGroupId()`

**Comment by kingthorin** [comment]
Is that a length requirement or a character requirement? (Meaning does it have to be a leading 0 or just something in the existing set)

**Comment by axelfontaine** [comment]
Both

**Comment by kingthorin** [comment]
Well either it has to be zero or not. It can’t really be both.

**Comment by axelfontaine** [comment]
The length is wrong (16 hex chars instead of 17) and the first char has to be 0.

**Comment by kingthorin** [comment]
There we go, that actually answers the question. Thank you.

**Comment by kingthorin** [comment]
https://aws.amazon.com/blogs/compute/longer-resource-ids-in-2018-for-amazon-ec2-amazon-ebs-and-amazon-vpc/

**Comment by kingthorin** [comment]
So is it literally 0 followed by 16hex or are they generated serially and the first character simply hasn’t rolled yet?

All the examples I see are zero but I couldn’t find anything definitive.

**Comment by bodiam** [comment]
Seems like a reasonable straightforward fix, would you be willing to provide a fix @axelfontaine ?

**Comment by bodiam** [comment]
I don't think they should start with a 0. If you look at the aws documentation, this is what it says:

https://aws.amazon.com/about-aws/whats-new/2018/02/longer-format-resource-ids-are-now-available-in-amazon-ec2/

The example used there is:

vpc-1234567890abcdef0

**Comment by kingthorin** [comment]
Can anyone point to documentation that supports `subnetId()` and `securityGroupId()` being 17 as well?

**Comment by axelfontaine** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resource-ids.html

**Comment by kingthorin** [comment]
Thank  you, I'll tweak my PR.
