### ISSUE TITLE
Invalid date 'February 29' as '1925' is not a leap year

### ISSUE THREAD

**Issue by Arroheim** [datafaker-net/datafaker#1098]
**Describe the bug**
If now date is a leap year, for example 2024.02.29, throws exception java.time.DateTimeException
Invalid date 'February 29' as '1925' is not a leap year

**To Reproduce**
// Current date must be February 29 and  leap year
Faker faker = new Faker();
faker.date().birthday(18, 99)

**Expected behavior**
Generates valid date

**Versions:**
 - OS: any
 - JDK: any
 - Faker Version: 1.8.1

**Additional context**
Need to add if here:
![image](https://github.com/datafaker-net/datafaker/assets/24206337/8fd2afbc-ce0c-4fc9-af69-4d901ab57449)

something like:
    if (dayOfMonth == 29){
        dayOfMonth = dayOfMonth-1;
    }

**Comment by bossm0n5t3r** [comment]
same here!

**Comment by merodwin** [comment]
me too

**Comment by snuyanzin** [comment]
This has already been fixed in later versions 
https://github.com/datafaker-net/datafaker/pull/954

please use the latest version e.g. 2.1.0

**Comment by snuyanzin** [comment]
2.0.2 also has this fix 
do you have the same issue while upgrading to 2.0.2?

**Comment by Arroheim** [comment]
I found the solution for my build.gradle.kts. May be it someone helps:

```
configurations.forEach { it.exclude("org.yaml", "snakeyaml") }
dependencies {
    implementation("org.yaml:snakeyaml:1.26")
    implementation("net.datafaker:datafaker:2.1.0")
}
```

**Comment by bodiam** [comment]
@Arroheim why are you excluding Snakeyaml, and what issues are you running into? The snakeyaml you hav mentioned above is full of security issues, don't use that one; Datafaker comes with Snakeyaml 2.2 which, as far as we know, doesn't have CVEs, so when you say: "Update to 2.1.0 has some difficults with snakeYaml", does that mean you might have a version conflict or so? Either way, I wouldn't recommend your above approach.

**Comment by snuyanzin** [comment]
I tend to think that introduction of `module-info` is the reason...

Ideally it shouldn't happen since snakeyaml is shaded

@Arroheim could you please double check whether datafaker 2.0.2 works without that hack?

**Comment by gdonoso94** [comment]
We've encountered this problem, too. This issue should still be open.

Updating to 2.1.0 in Java throws this when using `Locality`

```
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null
	at net.datafaker.providers.base.Locality.allSupportedLocales(Locality.java:103)
	at net.datafaker.providers.base.Locality.allSupportedLocales(Locality.java:49)
	at net.datafaker.providers.base.Locality.<init>(Locality.java:39)
	at net.datafaker.providers.base.BaseFaker.getProvider(BaseFaker.java:329)
	at net.datafaker.providers.base.ProviderRegistration.getProvider(ProviderRegistration.java:21)
```

We are instantiating a default Faker instance: `new Faker()`

Tried fixing `snakeyaml`, too. Doesn't work either...

**Comment by snuyanzin** [comment]
@gdonoso94 this is another issue and it is not clear how to reproduce it

please open a new issue and provide steps to reproduce

**Comment by snuyanzin** [comment]
@Arroheim thanks for checking, then not clear why it is happening... need to debug
I do notuse gradle... in maven projects i do not see this issue...
