### ISSUE TITLE
Faker.date().birthday() returns in invalid Date on Leap Day

### ISSUE THREAD

**Issue by Woermachine** [datafaker-net/datafaker#1104]
**Describe the bug**
`Faker().date().birthday()` is returning the invalid date February 29, 1959.

Theory: Today's day is February 19, 2024 so `birthday()` must not be account for leap days

Exception Thrown
> Invalid date 'February 29' as '1959' is not a leap year
> java.time.DateTimeException: Invalid date 'February 29' as '1959' is not a leap year
>at java.base/java.time.LocalDate.create(Unknown Source)
	at java.base/java.time.LocalDate.of(Unknown Source)
	at java.base/java.time.LocalDateTime.of(Unknown Source)
	at net.datafaker.providers.base.DateAndTime.birthday(DateAndTime.java:258)
	at net.datafaker.providers.base.DateAndTime.birthday(DateAndTime.java:233)

**To Reproduce**
Call `Faker().date().birthday()` on  February 19, 2024 

**Expected behavior**
Function should return only valid days

**Versions:**
 - OS: OSX 14.2.1 
 - JDK OpenJDK 17.0.7
 - Faker Version 1.8.1

**Additional context**
Platform: Android

**Comment by snuyanzin** [comment]
closing as duplicate https://github.com/datafaker-net/datafaker/issues/1098
it was fixed almost a half a year ago at https://github.com/datafaker-net/datafaker/pull/954
please use 2.0.2 or 2.1.0+

please use search before issue creation

**Comment by Woermachine** [comment]
Whoops. Thank you @snuyanzin
