### ISSUE TITLE
Possible JSON generation error

### ISSUE THREAD

**Issue by eliasnogueira** [datafaker-net/datafaker#1109]
## Description

The [JSON Schema Transformation](https://www.datafaker.net/documentation/schemas/#json-transformation) seems to generate an invalid JSON output when it generates more than 2 objects.

## Problem

When it generates 2 or more objects, the JSON starts as an Object instead of an Array.

## Steps to reproduce

Getting the example in the datafaker documentation from [JSON Schema Transformation](https://www.datafaker.net/documentation/schemas/#json-transformation) we have the following code:

```java
Schema<Object, ?> schema = Schema.of(
    field("Text", () -> faker.name().firstName()),
     field("Bool", () -> faker.bool().bool())
 );

JsonTransformer<Object> transformer = JsonTransformer.builder().build();
 String json = transformer.generate(schema, 2);
```

### Expected result

As it's generating 2 objects, the output must start as an Array

```json
[
   {
      "Text":"Nathalie",
      "Bool":false
   },
   {
      "Text":"Tamika",
      "Bool":true
   }
]
```

### Actual result

The output starts as an object.

```json
{
   {
      "Text":"Nathalie",
      "Bool":false
   },
   {
      "Text":"Tamika",
      "Bool":true
   }
}
```

### How to validate

There are two easy ways to validate.

#### Transform the output into a JSON object

1. Import the [json](https://mvnrepository.com/artifact/org.json/json/20240205) Java library
2. Use the same code as in the docs,  using the generated JSON output to create a JSON object

```java
 Schema<Object, ?> schema = Schema.of(
  field("Text", () -> faker.name().firstName()),
  field("Bool", () -> faker.bool().bool())
);

JsonTransformer<Object> transformer = JsonTransformer.builder().build();
String json = transformer.generate(schema, 2);

 new JSONObject(json); // an exception will happen here
```

#### Validate the output in any online JSON formatted

1. Access https://jsonchecker.com/
4. Copy the output from the _Actual results_ section
5. Check the output

## Versions

 - OS: MacOS 14.3.1
 - JDK: openjdk version "21" 2023-09-19
 - Faker version: 2.1.0

## Additional information

I can in the [JSONTest](https://github.com/datafaker-net/datafaker/blob/main/src/test/java/net/datafaker/formats/JsonTest.java) that the [testGenerateFromSchemaWithLimit](https://github.com/datafaker-net/datafaker/blob/main/src/test/java/net/datafaker/formats/JsonTest.java#L33C10-L48) test expects, wrongly, the curly brackets when there are 2 or more data.

I believe the logic should be:
- only one `limit`: curly brackets are added at the beginning and end of the output
- two or more `limit`: square brackets are added at the beginning and end of the output

I'll be more than happy to contribute to this fix if you guys agree.

**Comment by snuyanzin** [comment]
As a WA it could be handled with help of this
```java
JsonTransformer<Object> transformer = JsonTransformer.builder().formattedAs(FormattedAs.JSON_ARRAY).build();
```
after that there will be square brackets

**Comment by snuyanzin** [comment]
>I'll be more than happy to contribute to this fix if you guys agree.

there is already some logic for handling this, may be need to twek in a better way when FormattedAs.JSON_ARRAY and when `FormattedAs.JSON_OBJECT`  should be used...

feel free to contribute here

**Comment by eliasnogueira** [comment]
@snuyanzin Thank you for the explanation.

Wouldn't be better to remove the `Formatter` and add the logic during the generation?
I'm suggesting it because more than 2 objects will be wrongly generated if we don't use the `formattedAs()`. I can't see any use case as the consumer would generate the objects starting the JSON file with a curly brace.

**Comment by eliasnogueira** [comment]
Btw, I will add an issue to update the docs with the mention of the `formattedAs()` method.

**Comment by snuyanzin** [comment]
>Wouldn't be better to remove the Formatter and add the logic during the generation?

I remember the was some questionable cases, if we can double check that everything is remained covered then probably yes could be removed

**Comment by snuyanzin** [comment]
I'm ok to use jackson however in this case we probably should shade it as well (in order to prevent clashing of deps in case someone uses datafaker from on side and from another side has dependency on a different jackson version)

Probably we could still keep `JsonTransformerBuilder` NON deprecated and use it it pass ObjectMapper flags in case of non default behavior is  required, e.g. order of map objects  by keys (suddenly i faced thatdefault behavior for this sometimes changes between jdk17 and jdk21)

**Comment by eliasnogueira** [comment]
What I meant was not using Jackson. I used it to illustrate its behavior for objects or arrays.

**Comment by snuyanzin** [comment]
ok then the question: how inside `generateJson` we could answer a question "should we generate an object or an array with length 1?"

**Comment by kingthorin** [comment]
Can this be closed?

**Comment by eliasnogueira** [comment]
> Can this be closed?

@kingthorin I'm, slowly, working on it. Can we keep this open?
Thank you!

**Comment by bodiam** [comment]
@eliasnogueira would you like to have this change into Datafaker 2.2? I haven't picked a release date yet, but probably within a month or so.

**Comment by eliasnogueira** [comment]
> @eliasnogueira would you like to have this change into Datafaker 2.2? I haven't picked a release date yet, but probably within a month or so.

Most likely I will place the PR tomorrow. :-)

**Comment by eliasnogueira** [comment]
@bodiam @kingthorin @snuyanzin 
I've added this PR https://github.com/datafaker-net/datafaker/pull/1134

It adds one more ability to the `JsonTransformer` and it's explained in the PR.
It's ok if you guys disagree with the proposal.

**Comment by snuyanzin** [comment]
I'm going to close it since the PR is merged now
https://github.com/datafaker-net/datafaker/pull/1134
