### ISSUE TITLE
Duplicate faker groups (Money and Currency)

### ISSUE THREAD

**Issue by panilya** [datafaker-net/datafaker#1112]
It seems we have 2 faker groups with similar fakers: [src/main/java/net/datafaker/providers/base/Money.java](https://github.com/datafaker-net/datafaker/blob/main/src/main/java/net/datafaker/providers/base/Money.java) and [src/main/java/net/datafaker/providers/base/Currency.java](https://github.com/datafaker-net/datafaker/blob/main/src/main/java/net/datafaker/providers/base/Currency.java).

The best solution I see to this issue is to deprecate one of the faker groups. I want to hear your thoughts and what faker group we should deprecate.

After discussion, I will be happy to contribute to this change.

**Comment by bodiam** [comment]
Good point. Might make sense to deprecate Currency,  delegate everything to Money, and we will remove Currency in 2.4 or 3.0. Would that work?

**Comment by panilya** [comment]
Yes, I think this will work.

+1 to remove deprecated Currency faker group in the 3.0 version

**Comment by snuyanzin** [comment]
I wonder why  have this class at all?
there is a java class `java.util.Currency` which could be reused instead of duplicating logic with `yaml` file which is slower

**Comment by bodiam** [comment]
@snuyanzin good question. I think faker.Currency is pre Java 8, while util.Currency was introduced in Java 8. Might make sense to migrate it.

**Comment by snuyanzin** [comment]
In fact it is present in Java since 1.4 ... 
In javadocs it is stated that it done based on ISO 4217, so probably would be better to use it

**Comment by snuyanzin** [comment]
@bodiam , @panilya am I right that this one now can be closed?

**Comment by panilya** [comment]
I think so.

Maybe it also makes sense to leave somewhere a reminder to delete Currency faker in the 3.0.0 release

**Comment by bodiam** [comment]
I think it will be deleted in version 2.4.0 or 2.5.0. I know it's not entirely "semver", but 3.0 to me sounds like a huge milestone, not just the removal of a class which is is probably used by only a small set of our users.

**Comment by kingthorin** [comment]
The code/javadoc have the removal todo details.
