### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by bodiam** [datafaker-net/datafaker#1113]
* [ ] Update version numbers in the documentation
* [ ] Create release notes
* [x] Remove 2.1.1 References and update to 2.2.0
* [ ] Publish new provider list in the documentation

**Comment by kingthorin** [comment]
2.1.1 and 2.2.0 😉

**Comment by bodiam** [comment]
Ehm, yes, I think I got confused somehow. Thanks for fixing!

**Comment by bodiam** [comment]
Okay, I'll release a new version at 1000 stars. We're close.

**Comment by kingthorin** [comment]
https://x.com/kingthorin_rm/status/1776647754174857677?s=46

**Comment by bodiam** [comment]
I'm in the process of preparing for the release, but it seems everything has changed now, and there's now a thing called Central Portal. I'm not sure at the moment on how to publish, so contacted support on this.

**Comment by snuyanzin** [comment]
No idea what was done however it seems to be completed (> 1000 stars)
thanks everyone involved

**Comment by bodiam** [comment]
Oh wow. Did someone buy some stars or so? Well, only fair to release a new version then I guess?

**Comment by kingthorin** [comment]
I think it was me. I was in one of those Twitter threads yesterday where people drop their GitHub profiles and talk about what they're working on and mentioned the project 🙂

Ya I think it's good to go 😁

**Comment by snuyanzin** [comment]
yep, thanks a lot
and also thanks to @eliasnogueira https://twitter.com/eliasnogueira/status/1781681978770608335 i guess

**Comment by bodiam** [comment]
Love it! Thank you all for your amazing work on the library and the promotion of it, it's still great to see the energy around this. To give some insights: we had 464000(!!!) downloads, and it's still growing steadily, (we might break 500000 per month this month!)

Thanks again, love your work!!
