### ISSUE TITLE
weapons feature request

### ISSUE THREAD

**Issue by TatsuyaD7** [datafaker-net/datafaker#112]
I read the issues of javafaker and kown that this is the fork repo which mostly update, so i create a same issue, hoping someone fix it

**Is your feature request related to a problem? Please describe.**

There are many weapons in modern society.Please consider adding its feature.

**Describe the solution you'd like**

Weapon type,  The bullet diameter, manufacture etc

**Comment by snuyanzin** [comment]
Hi @TatsuyaD7 since 1.2.0 datafaker allows to create custom providers, for more details and examples please have a look at https://www.datafaker.net/documentation/custom-providers/

Also since we all are volunteers here, contributions are more than welcome

**Comment by bodiam** [comment]
Hi @TatsuyaD7 , as @snuyanzin said, it's quite easy to make your own. We're happy to accept any PR in this project, which I think would be a better way to address this. I don't consider this an issue at the moment as such, so I'll close it for now, but happy to consider a PR to support this.
