### ISSUE TITLE
Support JPMS

### ISSUE THREAD

**Issue by DaiYuANg** [datafaker-net/datafaker#1130]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snuyanzin** [comment]
what is JPMS, any link description to the relevant info?
And why it couldn't be implemented as a customer provider and it should be as a part of datafaker?

Currently since there is no any info I tend to close it because of poor provided info

**Comment by DaiYuANg** [comment]
> what is JPMS, any link description to the relevant info? And why it couldn't be implemented as a customer provider and it should be as a part of datafaker?
> 
> Currently since there is no any info I tend to close it because of poor provided info

My bad, JPMS is java module `Modularity adds a higher level of aggregation above packages. The key new language element is the module—a uniquely named, reusable group of related packages, as well as resources (such as images and XML files) and a module descriptor specifying` support after jdk 9.

**Comment by snuyanzin** [comment]
and what is wrong with current version which already contains `module-info.java` in built jar?

**Comment by DaiYuANg** [comment]
> and what is wrong with current version which already contains `module-info.java` in built jar?

I am using 2.1.0 version and with gradle, it's show me `e: Module net.datafaker cannot be found in the module graph`
And I look up my local datafaker jar from maven downloaded
<img width="300" alt="截屏2024-03-17 02 34 36" src="https://github.com/datafaker-net/datafaker/assets/138393979/cb23ceb6-5994-4294-8fc6-b75abba838bb">
<img width="548" alt="截屏2024-03-17 02 35 02" src="https://github.com/datafaker-net/datafaker/assets/138393979/edea9437-3043-41ba-a8f5-ae65e3177dfe">
There is only one module-info.class, but it not belong to datafaker

**Comment by snuyanzin** [comment]
the latest relevant commit was done  at https://github.com/datafaker-net/datafaker/pull/1108
which is not released yet

**Comment by DaiYuANg** [comment]
> 最新的相关提交是在#1108完成的 ，尚未发布

Thanks for answer

**Comment by bodiam** [comment]
@DaiYuANg  can you please try the snapshot release to see if that works for you? It's quite stable, and we will release a new version very soon.
