### ISSUE TITLE
NullPointerException when using Faker#locality

### ISSUE THREAD

**Issue by f-cramer** [datafaker-net/datafaker#1170]
**Describe the bug**
I get a `NullPointerException` when calling `Faker#locality`. The message is `java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.toString()" because the return value of "java.nio.file.Path.getFileName()" is null`

**To Reproduce**
https://github.com/f-cramer/datafaker-npe
Just run `gradlew test` to reproduce

**Expected behavior**
Initialization of Locality should complete without throwing an exception

**Versions:**
 - OS: Windows 11, could also reproduce in a Github Action running on ubuntu-latest
 - JDK 17
 - Faker 2.2.1, but seems to happen since at leat 2.1.0

**Comment by bodiam** [comment]
Thanks for reporting, looking into it!

**Comment by bodiam** [comment]
2.2.2 has been released to address this issue.

**Comment by f-cramer** [comment]
That great. Thanks for the very quick fix.
