### ISSUE TITLE
Regexify method doesn't recognise "^" and "$" chars in datafaker before 2.2.0.

### ISSUE THREAD

**Issue by maxtar** [datafaker-net/datafaker#1209]
**Describe the bug**
Faker().regexify() doesn't take into account "^" and "$" chars.

**To Reproduce**
```kotlin
Faker().regexify("^\d{10}$")
```

will make something like `^4111968277$`

**Expected behavior**

In regex "^" char means start of string and "$" - end of string. regexify must recognise this chars. Result must be `4111968277`.

**Versions:**
 - JDK 11
 - Faker Version 1.9.0

**Comment by snuyanzin** [comment]
This is not a datafaker issue, it is the issue of undelying library https://github.com/mifmif/Generex which was used before 2.2.0

Starting 2.2.0 we use another library https://github.com/curious-odd-man/RgxGen
and it doesn't have this problem
So either bump your dependency or contribute a PR to have similar support in 1.x

**Comment by bodiam** [comment]
Yes to what @snuyanzin said. We don't really support 1.x anymore, nor do we support such old versions of Java, but if you're willing to make a PR for this, I'm happy to release a new 1.x version. But it's recommended to upgrade.

**Comment by maxtar** [comment]
I've got it. But Java 11 is LTS. And we counldn't upgrade to new version now.
I will think about PR thank you.

**Comment by kingthorin** [comment]
You could just concatenate the pre/post-fix after generating the regexified value.

**Comment by maxtar** [comment]
> You could just concatenate the pre/post-fix after generating the regexified value.

I did it. But remove prefix and sufffix before calling regexify.

**Comment by bodiam** [comment]
@maxtar It's a bit beyond the scope of this issue, but Java 11 LTS has only but only extended support available, and has been superseded by Java 17 LTS and Java 21, which is also LTS. 

Either way, still happy to make a 1.x release when it's fixed.

**Comment by bodiam** [comment]
Hi @maxtar , we're aware of this issue, and as said before, happy to accept PRs, even on the 1.x branch, but for now I'll close the issue to clean things up a little.
