### ISSUE TITLE
Feature request: add support to generate a random PNG/SVG.

### ISSUE THREAD

**Issue by erikpragt-connectid** [datafaker-net/datafaker#1221]
We currently have a testcase in which we pass in some data, such as:

```
 "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAR+ElEQVR42u1ceVDUx5f/fGc4dDiCIAoEFCQYwaOUwgPYaDxiiGWiCaJokp/......... much more here"
```

It might be nice if we could generate random images like this too, something like `faker.image().base64PNG()` or so.

See for references:
* https://github.com/darpandodiya/random-image-generator/blob/master/RandomImageGenerator.java
* https://codereview.stackexchange.com/questions/244123/fastest-way-to-create-random-pixel-image
* https://stackoverflow.com/questions/56825653/i-wanted-to-make-an-random-image-generator-but-it-does-not-work

and:

* https://stackoverflow.com/questions/30093680/how-to-loop-a-81-svg-imagegenerated-by-java-to-get-a-88-svg-image

(I'm happy to build this myself, I just leave it here as a reminder)

Design considerations/questions?
* It would perhaps be nice to use the same logic to generate vector and binary image formats.
* Perhaps generating a base64 and binary output should be possible?

**Comment by snuyanzin** [comment]
should it be closed now or something else should be implemented?
