### ISSUE TITLE
Password generation does not always contain a lowercase letter

### ISSUE THREAD

**Issue by andriy-lendyel** [datafaker-net/datafaker#1250]
Password generation does not always contain a lowercase letter. It would be nice to fix this. Here is the test to reproduce this issue.

```java
import net.datafaker.Faker;
import org.junit.jupiter.api.RepeatedTest;

class PasswordTest {

    private static Faker FAKER = new Faker();

    @RepeatedTest(100)
    void passwordTest() {
        String password = FAKER.internet().password(8, 16, true, true, true);

        assertTrue(
            password.chars().anyMatch(i -> Character.isLetter(i) && Character.isLowerCase(i)),
            password + " password should contain lower case character."
        );
    }
}
```

**Comment by kingthorin** [comment]
I guess we could add another method with a fourth Boolean but really logically someone could very well choose a password that is full caps 🤷‍♂️

Also in the next release we'll be deprecating the password methods and suggesting `Text#text(Text.TextRuleConfig)` instead.

**Comment by snuyanzin** [comment]
nobody says that `internet().password`gives you such guarantee, if you need such guarantee then use `Text#text(Text.TextRuleConfig)` as mentioned above

**Comment by crimsonvspurple** [comment]
> I guess we could add another method with a fourth Boolean but really logically someone could very well choose a password that is full caps 🤷‍♂️
> 
> Also in the next release we'll be deprecating the password methods and suggesting `Text#text(Text.TextRuleConfig)` instead.
> 
> * [Mark Internet#pass deprecated #1245](https://github.com/datafaker-net/datafaker/pull/1245)
> * [Add doc about advanced char sequence generation #1246](https://github.com/datafaker-net/datafaker/pull/1246)

Hi.

Is it possible to make the new pass recommendation (TextSymbolsBuilder...) to optionally utilize SecureRandom?

If not, will you please add this feature?
