### ISSUE TITLE
Memory leak for seeded random use case

### ISSUE THREAD

**Issue by vitaly-ivanov** [datafaker-net/datafaker#1269]
**Describe the bug**
The [PROVIDERS_MAP](https://github.com/datafaker-net/datafaker/blob/main/src/main/java/net/datafaker/providers/base/BaseFaker.java#L34) cache size increases when using the seeded random functionality with the [doWith](https://github.com/datafaker-net/datafaker/blob/main/src/main/java/net/datafaker/providers/base/BaseFaker.java#L68) method. 

This issue is similar to https://github.com/datafaker-net/datafaker/issues/883.

**To Reproduce**
Code to reproduce is here:
https://github.com/vitaly-ivanov/datafaker-memory-leak/blob/main/app/src/main/kotlin/org/example/App.kt

**Expected behavior**
I think the cache should not be filled while using the `doWith` block method as it wraps the callable.

**Versions:**
 - OS: macOS 14.5
 - JDK 21
 - Faker Version 2.2.2

**Additional context**
Our aim is to generate the same values for the same random seed. The number of values can be very large.

[The fix](https://github.com/datafaker-net/datafaker/commit/4ce8d05b87969716cf386ac14045b7d0d3ecd675) does not work in this case because new instances of the `RandomService` and `Random` classes are used. 

But even if the random seed is the same, the equals method returns false because `java.util.Random' does not override the `equals' and `hashCode' methods.

**Comment by snuyanzin** [comment]
the issue is same and known, even more this behavior was mentioned in comments
so I don't see a reason to have another open issue

**Comment by vitaly-ivanov** [comment]
@snuyanzin I see, the problem is the same. Could you consider renaming #1263 as it's barely searchable as it is.

**Comment by snuyanzin** [comment]
renamed
