### ISSUE TITLE
Create a dictionary of obscene words

### ISSUE THREAD

**Issue by asolntsev** [datafaker-net/datafaker#1272]
**Is your feature request related to a problem? Please describe.**
I suggest to create a dictionary of obscene words. It may be useful for testing spam filters, blog prettifiers etc.

I can provide the list in English, Estonian and Russian.

**Describe the solution you'd like**
It could look like this:

```java
  Faker faker = new Faker(new Locale("en", "US"));
  String blacklistedWord = faker.dictionary().obsent(); // fuck | shit | ass

  Faker faker = new Faker(new Locale("ru", "RU"));
  String blacklistedWord = faker.dictionary().obsent(); // жопа
```

**Additional context**
It also will be very motivating feature for people to submit their pull request. Imagine they need to add "fuck" on their languages. The easiest and funniest PR ever possible! :)

**Comment by kingthorin** [comment]
Did you truncate the method name on purpose? Shouldn't it be `obscenity`?

Anyway yes I support this idea.

Though I (we) would have zero ability to review other languages.

Also we should keep in mind (perhaps even document) that while some words/phrases are just "bad" some are truly hateful/hurtful and that's hard to nail down (even in languages that you are familiar with).

**Comment by bodiam** [comment]
Just a word of caution: we recently had a production issue with another faker library which was generating some offensive language which ended up in a customer demo, which was a bit of an unfortunate experience.

**Comment by kingthorin** [comment]
Good point, it is also a perfect case for a custom faker with their own yaml or whatever.

**Comment by snuyanzin** [comment]
how about not only obscene words but also obscene expressions?

**Comment by bodiam** [comment]
I'm not a fan of either :)

**Comment by bodiam** [comment]
@snuyanzin @asolntsev if you're realllllllllly keen, you can always use Fallout quotes for the spam filtering: 

https://github.com/datafaker-net/datafaker/blob/5a4aa0f8db734ded1b7a8869c6a2502623e69efc/src/main/resources/en/fallout.yml#L109

**Comment by asolntsev** [comment]
@bodiam Sorry, I don't understand how.
To test spam filter, I need some provider that stably generate obscene words.
Fallout quotes don't suite because **only some** of them contain obscene words.  How can such a test stably work?

**Comment by kingthorin** [comment]
Just use a custom provider with your own yaml, then there are no concerns for the project.
