### ISSUE TITLE
Fix publishing of snapshots

### ISSUE THREAD

**Issue by bodiam** [datafaker-net/datafaker#1301]
Sonatype have changed something in their authentication setup, and now the snapshots aren't published anymore on every push. 

This should get fixed.

**Comment by asolntsev** [comment]
It's quite simple change. Instead of your real username+password, you need to use "access token".
You can generate it in https://oss.sonatype.org -> "Profile" -> "User Token":

<img width="493" alt="image" src="https://github.com/user-attachments/assets/3a71502f-7cdb-481e-8bec-bdd74a5363f0">

**Comment by bodiam** [comment]
Thanks, I'll have a look, just not sure where it's used.

**Comment by bodiam** [comment]
Okay, it's updated, and I've used this PR to test it: https://github.com/datafaker-net/datafaker/pull/1302
