### ISSUE TITLE
Add library API to C++

### ISSUE THREAD

**Issue by mhco0** [datafaker-net/datafaker#1348]
It would be nice to add the library to be used in C++ and with port on vcpkg or any other package manager.

**Comment by bodiam** [comment]
Hi @mhco0 , sorry, not sure what you mean. This is a Java library, how do you expect to use this? I believe you can use JNI to do this (see https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/invocation.html), but it's a bit beyond the scope of our project at the moment.

**Comment by mhco0** [comment]
Hi @bodiam, hope you doing well. Sorry, I should have express me better, but you're right, JNI already fulfill my needs.

Thanks!
