### ISSUE TITLE
ChineseIdNumber: Last digit is wrong 

### ISSUE THREAD

**Issue by ly1012** [datafaker-net/datafaker#1353]
**Describe the bug**

The last digit is wrong when generate Chinese Id Number.

Here is the current algorithm that is wrong.

| count %= 11 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| - | - | - | - | - | - | - | - | - | - | - | - |
| finalValue | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | X |

```java
    private static String idNumber(char[] res) {
        ...
        count += (res[16] - '0') * 2;
        count %= 11;
        return count == 10 ?
            String.valueOf(res) + "X" :
            String.valueOf(res) + count;
    }
```

**To Reproduce**

```java
    @Test
    void testChineseIdNumber() {
        Faker faker = new Faker(Locale.CHINA);
        String idNumber = faker.idNumber().valid();
        System.out.println(idNumber);
    }
```

**Expected behavior**

correct algorithm:

| count %= 11 | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| - | - | - | - | - | - | - | - | - | - | - | - |
| finalValue | 1 | 0 | X | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 |

```java
    private static final char[] checkCodes = {'1', '0', 'X', '9', '8', '7', '6', '5', '4', '3', '2'};

    private static String idNumber(char[] res) {
        ...
        count += (res[16] - '0') * 2;
        count %= 11;
        return String.valueOf(res) + checkCodes[count];
    }
```

or

```java
    private static String idNumber(char[] res) {
        ...
        count += (res[16] - '0') * 2;
        count = (12 - count % 11) % 11;
        return count == 10 ?
            String.valueOf(res) + "X" :
            String.valueOf(res) + count;
    }
```

**Versions:**
 - OS: macOs Sonoma 14.4.1
 - JDK: 17
 - Faker Version: 2.3.1

**References**

https://en.wikipedia.org/wiki/Resident_Identity_Card#Identity_card_number

**Comment by kingthorin** [comment]
Thanks @ly1012 do you plan to submit a fix as well?
