### ISSUE TITLE
Hacktoberfest 2024 participation

### ISSUE THREAD

**Issue by gvrettos** [datafaker-net/datafaker#1400]
I hope this is the right spot to ask something like this. 😃 

I would like to ask if you participate in the [hacktoberfest](https://hacktoberfest.com/) event. I do not see any tags or the related topic.
Could I ask for specific PRs to be annotated with **hacktoberfest-accepted** label?

**Comment by kingthorin** [comment]
I'm fine with that as long as we aren't getting spammy PRs.

**Comment by gvrettos** [comment]
Thank you!
I have some PRs in mind to work on and open during the next days. I do not think they will be spammy. 😃
