### ISSUE TITLE
Commit to master?

### ISSUE THREAD

**Issue by bodiam** [datafaker-net/datafaker#1421]
Hi @asolntsev ,

I'm not sure what happened, but did your last commits go directly to master? If so, how did you manage to do that? I was under the impression that every change needed a PR according to GitHub settings. Just curious what happened here.

Cheers,
Erik

**Comment by asolntsev** [comment]
Hi @bodiam .
No, I am pretty sure I didn't commit anything to master branch.

What commit do you mean? Is it 87a38039e96c42cef1af300f2b3 "improve test for faker.expression" (Nov 1, 2024)?

It was included in PR https://github.com/datafaker-net/datafaker/pull/1419/commits
![image](https://github.com/user-attachments/assets/ac359e21-069f-4c2d-8922-b49659e6a689)

(yes, not related directly to that PR - just this test failed a lot when I was working on that PR).

**Comment by kingthorin** [comment]
There's a chance I had used squash and merge in another repo and the mobile app kept that as its default. Sometimes that can make it look like a direct push vs a merge commit.

**Comment by asolntsev** [comment]
Github suggests 3 options to merge PRs. And remembers the last selected one. 
In case of "good" PRs (that contain few reasonable valuable commits) I highly recommend "Rebase and merge" option.
This creates a clear linear git history. No merge commits!

<img width="349" alt="image" src="https://github.com/user-attachments/assets/986d218a-6399-470d-b1f3-3250bba80615">

**Comment by bodiam** [comment]
I think I was indeed looking at those commits indeed. I couldn't find the associated PR, so I was wondering what happened. No worries, I just think I don't understand how Github works and how you can associate a commit with a PR or so.

**Comment by asolntsev** [comment]
There is no any problems with github. :)

I think it's just not needed to associate commits with PRs post-factum. :)
There is an author and date, this is the only important information. ;)

**Comment by snuyanzin** [comment]
In fact association is still present and you can navigate from commit to commit to the PR under which it was merged.
Even if explicit link from message was removed (it will be removed only from log message however not from all the places).

To see the PR just go to the commit itself and you see the link in top left under commit message
![Screenshot from 2024-11-02 08-55-56](https://github.com/user-attachments/assets/1aa3480f-8f39-43d7-b128-876976e3c847)

**Comment by bodiam** [comment]
@snuyanzin thanks, I didn't know that, that helps!
