### ISSUE TITLE
Add "java.time.temporal.ChronoUnit" support to "DateAndTime" provider

### ISSUE THREAD

**Issue by vadeg** [datafaker-net/datafaker#1430]
**Is your feature request related to a problem? Please describe.**

With `DateAndTime` provider it is not very convenient to generate dates in the future on in the past with a time shift more than a day. `java.util.concurrent.TimeUnit` which is used as an input argument in`DateAndTime` provider has the maximum granularity of a day.

**Describe the solution you'd like**

Add methods to DateAndTime provider which accepts `java.time.temporal.ChronoUnit` to define time intervals. 
For example if I need to generate a date 5 month in the future instead of this

```java
Timestamp date = faker.date().future(5 * 30, TimeUnit.DAYS);
System.out.println(date);
```

developers can write this:

```java
Timestamp date = faker.date().future(5, ChronoUnit.MONTHS);
System.out.println(date);
```

**Describe alternatives you've considered**

Alternative is to use `TimeUnit.DAYS` as a base unit and add required number of days to it to get desired month or year.

One can try to do the following:

```java
Timestamp date = faker.date().future(5, TimeUnit.of(ChronoUnit.MONTHS));
```

and immediately figure out that `TimeUnit` doesn't support conversion of `ChronoUnit` bigger than `DAYS`

**Additional context**

`java.util.concurrent.TimeUnit` was added in Java 1.5.  That was years before [JEP 150](https://openjdk.org/jeps/150) has been introduced which added normal date and time units support to Java. The package name also speaks for itself that it is not intended for date and time usage. Before then there were no normal time unit manipulation in Java. I would assume `TimeUnit` only stays in Java because of backward compatibility.

**Comment by kingthorin** [comment]
https://github.com/datafaker-net/datafaker/pull/1210

**Comment by bodiam** [comment]
Hi @vadeg , thanks for the suggestion, feel free to add a PR for this if you need this.

**Comment by bodiam** [comment]
Hi @vadeg , closing this for now to clean up open issues. If you, or anyone else, is interested to contribute to this feature, you're more than welcome to.

**Comment by kingthorin** [comment]
The newer provider `TimeAndDate` already allows this. It is based on TimeUnit not ChronoUnit but that's easily worked around if it actually matters.

Per: https://stackoverflow.com/a/35744437/7718222 since Java 9
> `TimeUnit.toChronoUnit()` // returns a ChronoUnit
> `TimeUnit.of(ChronoUnit chronoUnit)` // returns a TimeUnit

**Comment by vadeg** [comment]
@kingthorin this will work only with units Les than day. I described it above.
