### ISSUE TITLE
"DateAndTime" and "Time" providers - support `DateTimeFormatter` as an argument

### ISSUE THREAD

**Issue by vadeg** [datafaker-net/datafaker#1431]
**Is your feature request related to a problem? Please describe.**

If I need to generate date or time as String I need to provide a `pattern` argument. Pattern is a String where user can put anything. If "anything" is not a pattern then it would fail of course. Java also has a set of predefined widely used patterns defined in `java.time.format.DateTimeFormatter` which can not be reused.

**Describe the solution you'd like**

Add additional methods to `DateAndTime` and `Time` providers which accepts `DateTimeFormatter` as an input argument. In this case date and time generators could be done like this:

```
// For date and time
faker.date().future(5, TimeUnit.DAYS, DateTimeFormatter.ISO_DATE);

// For date
faker.time().future(5, ChronoUnit.SECONDS, DateTimeFormatter.ISO_DATE);
```

**Describe alternatives you've considered**

Alternative 1 - redefine date / time pattern

```java
faker.date().future(5, TimeUnit.DAYS, "yyyy-MM-dd");
```

It is very easy to make a mistake and instead of `2024-11-06` get `2024-22-08`

Alternative 2 - Format by yourself

```java
Timestamp date = faker.date().future(5, TimeUnit.DAYS);
String formattedDate = DateTimeFormatter.ISO_DATE.format(date.toLocalDateTime());
```

**Comment by kingthorin** [comment]
https://github.com/datafaker-net/datafaker/pull/1210

**Comment by bodiam** [comment]
Hi @vadeg , thanks for the suggestion. I'm not a huge fan of this myself, Datafaker is meant to generate data, not format it (besides our SQL, JSON, etc schemas), and the "Format it yourself" part seems like such a short bit of extra code that I'm not sure if it's worth adding it to Datafaker.

**Comment by bodiam** [comment]
Hi @vadeg , closing this for now to clean up open issues. If you, or anyone else, is interested to contribute to this feature, you're more than welcome to.
