### ISSUE TITLE
"DateAndTime" provider - Add methods to generate random `java.time.Instant`

### ISSUE THREAD

**Issue by vadeg** [datafaker-net/datafaker#1432]
**Describe the solution you'd like**

Add methods to `DateAndTime` provider which could generate `java.time.Instant` instances. `Instant` is very convenient to use for generating other types of date and time, e.g. `LocalDateTime`, `OffsetDateTime` etc. 

**Describe alternatives you've considered**

Alternative is to convert `java.sql.Timestamp` or `java.util.Date` to Instant and then to a required type.

**Additional context**

Besides the fact that `java.sql.Timestamp` and `java.util.Date` are still in use Java has more convenient classes to work with date and time. But even in his old era engineers prefer to use [Joda time](https://www.joda.org/joda-time/) rather than plain `java.util.Date` or `java.sql.Timestamp`. 
I would assume that this provider has been created long time ago, haven't got enough attention from these days and slightly outdated.

**Comment by kingthorin** [comment]
https://github.com/datafaker-net/datafaker/pull/1210

**Comment by bodiam** [comment]
Hi @vadeg , thanks for the suggestion, feel free to add a PR for this if you need this. Please keep in mind that we neither support `java.sql.Timestamp` nor `java.util.Date` anymore, but of course happy to support Time API

**Comment by kingthorin** [comment]
I started to add this but really it's a one or 3 liner depending how you implement it. So it doesn't really seem helpful.

```java
 public Instant instant() {
    return Instant.ofEpochMilli(faker.random().nextLong());
}
```

**Comment by vadeg** [comment]
@kingthorin this is a basic block for other generators.

**Comment by kingthorin** [comment]
If you're committed to it fire in a PR 🤷‍♂️
