### ISSUE TITLE
Faker with different Locale does not seem to work

### ISSUE THREAD

**Issue by isalvadori** [datafaker-net/datafaker#1454]
**Describe the bug**
I am trying to use the Faker with a different Locale ("de"), but it doesn't seem to be working, as I keep getting results based on the default en Locale.

**To Reproduce**
```
Faker faker = new Faker(new Locale("de"));
for(int i = 0; i < 20; i++) {
	System.out.println(faker.address().city());
}
```

**Expected behavior**
I would expect some German cities names, instead I get, for instance 
```
East Cristopherstad
Josefville
Port Ofeliaton
Jeffryside
West Lashunda
North Dexterport
West Joetteside
Lake Herta
Breitenbergshire
Rudystad
Pfannerstillhaven
East Mildredmouth
Durganton
Dariaton
Ratkeview
North Garland
Port Shantafort
Port Berrychester
Lake Arlashire
West Percyberg
```

**Versions:**
 - OS: linux
 - JDK java 17
 - Faker Version 2.4.2

**Additional context**
I also tried with other Locale ("it", "ar") and the result is the same.
I checked with `faker.locality().allSupportedLocales()` and these should all be supported Locale.

**Comment by kingthorin** [comment]
A Locale being supported just means there is "a" faker specific to that locale, not necessarily that there is "full" support across all fakers.
Also if something is resolved for a particular Locale doesn't necessarily mean it's "real" data it could be derived from other components/details (as seems to be the case for "de" city names).

Looking at the data file for "de" it seems the city names are truly faked based on first names:
https://github.com/datafaker-net/datafaker/blob/59eebb9cf32e5511b9254b364b1e3aa3d8b6a7b7/src/main/resources/de.yml#L16-L20

If you know a good source of city names for the Locales you care about please feel free to fire in some PRs 😀

**Comment by snuyanzin** [comment]
> I would expect some German cities names, instead I get, for instance

1. Based on what line in doc this expectation is?
2. IIRC it is a wrong expectation, in fact it tries to get data from files related to the specified locale
2.1 Ideally there should be data in corresponding language, if you are talking about `de` then in German
2.2 However it doesn't mean that cities should be limited to German cities only

**Comment by isalvadori** [comment]
> Also if something is resolved for a particular Locale doesn't necessarily mean it's "real" data it could be derived from other components/details (as seems to be the case for "de" city names).
> 
> Looking at the data file for "de" it seems the city names are truly faked based on first names:
> 
> https://github.com/datafaker-net/datafaker/blob/59eebb9cf32e5511b9254b364b1e3aa3d8b6a7b7/src/main/resources/de.yml#L16-L20
> 

If I look at the file you sent here, for instance, the city names should be taken from this list

```
      state: [Baden-Württemberg, Bayern, Berlin, Brandenburg, Bremen, Hamburg, Hessen, Mecklenburg-Vorpommern, Niedersachsen, Nordrhein-Westfalen, Rheinland-Pfalz, Saarland, Sachsen, Sachsen-Anhalt, Schleswig-Holstein, Thüringen]
```

but also this does not seem to be the case, as I only get US states. So, it seems the file is just ignored...?

**Comment by kingthorin** [comment]
There are states not cities

**Comment by bodiam** [comment]
Hi @isalvadori , thanks for reporting, but as written above, there simply aren't any cities translated to German yet. However, if you want them in the library, you're more than happy to contribute, and we're willing to help wherever we can. 

As a starting point, it might be good to look at `pt.yml` or `pl.yml`, these contain translated cities.

Also, I'm not sure what you mean with the states.

Given the following code:

```
    @RepeatedTest(10)
    void germanAddress() {
        Faker DE_FAKER = new Faker(new Locale("de"));

        System.out.println("city: " + DE_FAKER.address().city());
        System.out.println("state: " + DE_FAKER.address().state());
    }
```

When I run this, I get this as the output:

```
city: Groß Aysehagen
state: Rheinland-Pfalz
city: Süd Carolinberg
state: Mecklenburg-Vorpommern
city: Süd Mika
state: Brandenburg
city: Treffheim
state: Niedersachsen
city: Charlottaberg
state: Bayern
city: Fitschenhagen
state: Berlin
city: Linndorf
state: Baden-Württemberg
city: Tangburg
state: Baden-Württemberg
city: West Stephan
state: Hessen
city: Neu Lucienland
state: Sachsen
```

Those look like German states to me?

**Comment by isalvadori** [comment]
Yes, sorry. I am working in OSGi and I tried to repackage your jar into an osgi bundle.
I wasn't packaging the resources such as the yml files properly, and so it couldn't find the de.yml file.
Now I managed to get it work.
Sorry, and thanks for the support.

**Comment by kingthorin** [comment]
Thanks for letting us know.
