### ISSUE TITLE
Dark Soul Feature Request

### ISSUE THREAD

**Issue by NowhereTo** [datafaker-net/datafaker#159]
**Is your feature request related to a problem? Please describe.**
[From] Java-faker's Feature Request about Dark Soul.

**Describe the solution you'd like**
Add stuff in Dark Soul to datafaker.

**Comment by SickDawn** [comment]
@NowhereTo Ok, I see your issue now. I'm glad to solve this!

**Comment by bodiam** [comment]
@NowhereTo @SickDawn love it! Thanks for your input, I'm happy to accept a PR related to this.  I don't consider this an issue at the moment as such, so I'll close it for now, but happy to accept a PR to support such a feature!

**Comment by bodiam** [comment]
For inspiration, these a 2 great PRs which address a similar issue:

https://github.com/datafaker-net/datafaker/pull/155
https://github.com/datafaker-net/datafaker/pull/156

Thanks again!
