### ISSUE TITLE
Provide a (better) changelog

### ISSUE THREAD

**Issue by famod** [datafaker-net/datafaker#164]
First off, thanks a lot for this well maintained fork of javafaker. Very much appreciated!

IMO, this project is lacking a "proper" changelog. There is https://www.datafaker.net/releases/1.4.0/, but it's not linked from the Github releases page, so it's not that easily found when one has a very Github-centric workflow.
In fact, there are just tags, not "proper" releases here on Github.

I suggest create a release entry per actual release and place a link to the respective website page.
And to have a detailed list of changes I suggest to let GH auto-generate it (there is a button on the release creation page).

Also, being the maintainer of a GH project myself (https://github.com/gitflow-incremental-builder/gitflow-incremental-builder), I found Github milestones to be very handy.

**Comment by bodiam** [comment]
Hi @famod , thanks for your suggestion, we'll take it into consideration. If you'd like to setup a workflow for this, we're happy to take PRs on board.
