### ISSUE TITLE
Normalized phone_number

### ISSUE THREAD

**Issue by divinenickname** [datafaker-net/datafaker#168]
**Is your feature request related to a problem? Please describe.**
At my job I often use phone_number feature, but I work with phone numbers without any signs (only country code and digits).  I have to normalize phone numbers by myself. 

**Describe the solution you'd like**
It would be perfect to add new method `normalizedPhoneNumber()` to `PhoneNumber` class which returns normalized phone. 

Of cource I can implement it by myself

**Comment by bodiam** [comment]
Completely agree. I was looking at the same issue myself, or seems that at the moment it's very inconsistent if the international or local format is used. So I was thinking of keeping the current phone number method, but adding two extra methods, one for international and one for nationally formatted numbers. Would that work for you?

**Comment by divinenickname** [comment]
@bodiam yes, sounds good. I’ll research implementation ways at the end of the week

**Comment by snuyanzin** [comment]
what do you think about `normalizedPhoneNumber(Set<Character> characters2keep)`
where we could pass character with those a user is ok and `normalizedPhoneNumber()` which removes everything except digits?

e.g. for a phone number `(01837) 73 427` 
`normalizedPhoneNumber()` returns `0183773427`
`normalizedPhoneNumber(" ".chars().mapToObj(e -> (char) e).collect(Collectors.toSet()))` returns (01837)73427
`normalizedPhoneNumber("()".chars().mapToObj(e -> (char) e).collect(Collectors.toSet());)` returns 01837 73 427

**Comment by bodiam** [comment]
I'm fine with that, I'm mostly interested in having local numbers and international, like:

020584944 vs +9920584944

**Comment by bodiam** [comment]
I think this issue is not a real priority at the moment, so I'm going to close it. Happy to have international and normalized phone numbers if someone is keen picking it up though.

**Comment by panilya** [comment]
@bodiam I could take up this task. But, first, I wanted to know in a few words how it should look like. For example, in the `.yml` files add lists for international and local numbers, and have, for example, two methods `phoneNumberInternational` and `phoneNumberLocal`
