### ISSUE TITLE
Avatar URL changed

### ISSUE THREAD

**Issue by danielpassos** [datafaker-net/datafaker#219]
**Describe the bug**
The avatar URL is getting a `PermanentRedirect` from AWS

**To Reproduce**
Use whatever URL provided by [Avatar](https://s01.oss.sonatype.org/service/local/repositories/releases/archive/net/datafaker/datafaker/1.4.0/datafaker-1.4.0-javadoc.jar/!/net/datafaker/Avatar.html)
Example: https://s3.amazonaws.com/uifaces/faces/twitter/bradenhamm/128.jpg

**Expected behavior**
The URL should be updated

**Versions:**
 - Faker Version 1.5.0-SNAPSHOT

**Comment by bodiam** [comment]
Thanks for reporting. What do you propose we use instead?

**Comment by bodiam** [comment]
Fixed in 1f2802ee5d1bff2f83293367cc04b2694784aedd
