### ISSUE TITLE
Generate password with both lower and upper case guaranteed

### ISSUE THREAD

**Issue by roelmang** [datafaker-net/datafaker#243]
**Is your feature request related to a problem? Please describe.**
The password generator doesn't allow generating passwords with both lower and upper case in a consistent way.
Right now, the decision to have an upper or lower case character is defined by `this.faker.bool().bool()`
This will regularly generate an incorrect password, certainly if it's short.

**Describe the solution you'd like**
I want to be able to consistently generate a password with at least:
- a given minimum & maximum length
- 1 lower case
- 1 upper case
- 1 special
- 1 number

**Comment by panilya** [comment]
@roelmang You can take a look at `faker.internet().password()`.
There is a method:  `public String password(int minimumLength, int maximumLength, boolean includeUppercase, boolean includeSpecial, boolean includeDigit)`

**Comment by roelmang** [comment]
@panilya That's the method I'm reporting to not do what I want it to do. Please re-read my feature request.

**Comment by bodiam** [comment]
@roelmang what do you expect to happen when the password has length 3?

**Comment by roelmang** [comment]
Never thought I had to prove what I said, while you can just read it from the source code:
Given code:
`
import net.datafaker.Faker;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class ShowBodiam {

    static Faker FAKER = Faker.instance();

    public static void main(String[] args) {
        int count = 0;
        List<String> withoutLowerCase = new ArrayList<>();
        List<String> withLowerCase = new ArrayList<>();
        while (count++ < 1000000) {
            String password = generatePassword();
            if (containsLowerCase(password)) {
                withLowerCase.add(password);
            } else {
                withoutLowerCase.add(password);
            }
        }
        System.out.println("with lower case: " + withLowerCase.size());
        System.out.println("without lower case: " + withoutLowerCase.size());
        withoutLowerCase.stream().limit(10).forEach(System.out::println);
    }

    public static String generatePassword() {
        return FAKER.lorem().characters(6, 10, true, true, true);
    }

    public static boolean containsLowerCase(String pw) {
        return !Objects.equals(pw, pw.toUpperCase());
    }
}
`
Output:
with lower case: 804817
without lower case: 195183
D1NE3!
*2OMEN
47^%*7M
73%35Q&K
XC5^WM
FOK%350G
135ED$2V
W307%4
N9YE@5@KLI
JB@#1R

**Comment by snuyanzin** [comment]
I agree this generation is not the best way. 
Currently it does not provide guarantee of having lowercase in output guaranteeing only upper, digit and special.

At the same time there are other issues: 
It does special symbols are hardcoded without coverage all of them or possibility to exclude some of them
No way to support other symbols than from English alphabet.

So I would create a task to support fix that behavior and it should also fix an issue mentioned here

**Comment by bodiam** [comment]
>  the decision to have an upper or lower case character is defined by this.faker.bool().bool()

This is incorrect. If you call the method with a "true" for uppercase, the uppercase is always included, since that's happening a few lines above. You can see this in my output too. The lower case works differently indeed, but happy to accept any PR for this to force the creation of lowercase characters.

**Comment by snuyanzin** [comment]
@bodiam , @roelmang  you might be interested in having a look at https://github.com/datafaker-net/datafaker/pull/251
