### ISSUE TITLE
The generated image address cannot be accessed, and the same url is generated every time

### ISSUE THREAD

**Issue by 76SCORPIO** [datafaker-net/datafaker#247]
**Describe the bug**
faker.avatar().image()

**To Reproduce**
Code to reproduce

**Expected behavior**
I hope that each time the generated image address is different and can be accessed normally
**Versions:**
 - OS: [e.g. OSX]    macos
 - JDK    jdk11
 - Faker Version [e.g. 22]

**Additional context**

**Comment by bodiam** [comment]
This is fixed in 1.5.0, which has just been published. Thanks for reporting!

**Comment by 76SCORPIO** [comment]
Tried it and it fixed it.Thank you.
