### ISSUE TITLE
Missing data for ru and bg locales?

### ISSUE THREAD

**Issue by abeshenov** [datafaker-net/datafaker#263]
I upgraded from `com.github.javafaker:javafaker` to `net.datafaker:datafaker:1.5.0`, and it seems like some data is missing now.

The following worked as expected for `javafaker`:

```
new com.github.javafaker.Faker(new Locale("ru")).address().streetAddress();
// Example result: "Шевченко улица, 845"

new com.github.javafaker.Faker(new Locale("bg")).address().streetAddress();
// Example result: "бул. Лъчезар Станчев, 17"
```

However, this crashes with `RuntimeException`:

```
new net.datafaker.Faker(new Locale("ru")).address().streetAddress();
// RuntimeException: Unable to resolve #{Address.street_title} directive

new net.datafaker.Faker(new Locale("bg")).address().streetAddress();
// RuntimeException: Unable to resolve #{Address.street_title} directive
```

I went through all the locales listed in `README.md`, and this issue seems to arise precisely for `ru` and `bg`.

**Comment by snuyanzin** [comment]
yes, it's a known issue and it's in my todo list
https://github.com/datafaker-net/datafaker/pull/250#issuecomment-1194645762

I will try to have a look at it in coming days

**Comment by abeshenov** [comment]
@snuyanzin Thank you and sorry for reporting this again!

I can only confirm that this is something specific to `bg` and `ru`. Everything else works as expected.

**Comment by snuyanzin** [comment]
it looks it should be fixed within https://github.com/datafaker-net/datafaker/pull/270
I added there a test for several countries
@abeshenov  could you please double check if your issue is fixed?

**Comment by abeshenov** [comment]
@snuyanzin Yes, now everything works for me with `1.6.0-SNAPSHOT`. Thank you very much!
