### ISSUE TITLE
Add more passport number generators

### ISSUE THREAD

**Issue by panilya** [datafaker-net/datafaker#268]
**Is your feature request related to a problem? Please describe.**
At that moment, there are only 2 passport number generators. Am(American) and Ch(Chinese) passport number generator.

**Describe the solution you'd like**
Add support for more countries, at least for the EU.

**Comment by bodiam** [comment]
Good idea!

**Comment by bodiam** [comment]
Hi @panilya , I found this page: https://docs.microsoft.com/en-us/microsoft-365/compliance/sit-defn-greece-passport-number?view=o365-worldwide

I just added quite a few passport number to the code based on this.
