### ISSUE TITLE
Strange generation of 'PhoneNumber' faker

### ISSUE THREAD

**Issue by panilya** [datafaker-net/datafaker#277]
**Describe the bug**
I've been generating phone numbers in my project and noticed some strange and incorrect results.

**To Reproduce**
```
Faker faker = new Faker();
faker.phoneNumber().phoneNumber();
```

The result of 50 repeated generations:
```
755-482-2234
085-863-3865 x3172
1-065-305-4959 x8047
314.976.7963 x734
330-099-4886 x670
916.255.0603 x527
725-431-2485 x2418
212-342-1988
342-146-2804 x670
(085) 866-9161 x22174
952-205-3782 x28369
(116) 263-6437 x19870
(767) 394-5938 x16583
106-499-4984 x0279
742-522-5959 x09797
(369) 671-5077
(228) 198-2966 x883
1-308-449-2513 x34799
1-941-533-0634 x464
1-473-386-5272 x7908
(609) 208-8335 x1751
1-569-094-9768 x527
559.581.5058 x13411
372-047-9918 x8116
942.389.2238
955.419.1339 x350
(860) 978-1565 x11785
906-710-1553 x40711
1-226-999-7832 x309
510.265.6294 x3466
1-009-496-8327
1-070-132-9366 x88195
292.279.7325 x65075
1-891-998-7425
619-452-1971 x0025
(195) 188-3605
1-099-630-3627 x726
520-057-5025 x683
1-614-603-4667
356.356.3680 x787
(610) 582-2496 x3466
733.494.4426
746.041.2609 x2698
281-908-1136
(227) 044-7571 x869
1-922-095-8040 x7974
371.030.3800 x756
1-173-703-9945 x73683
1-011-256-6217 x0112
860.554.2778 x555
```

**Versions:**
 - OS: Windows 11
 - JDK: 11
 - Faker Version 1.5.0

**Comment by snuyanzin** [comment]
Probably would be helpful if you specify what exactly is incorrect

**Comment by panilya** [comment]
@snuyanzin For example this: `371.030.3800 x756`. 

`x756` is this correct?

**Comment by snuyanzin** [comment]
no idea, i'm not an expert in phone numbers, that's why put a comment about clarification like how to determine which one is correct and which one is not

**Comment by panilya** [comment]
@snuyanzin me too, but I don't think phone numbers should have `x###` at the end

**Comment by panilya** [comment]
Also, the fact that some numbers were generated in International Format, some with dots(don't know how)

**Comment by panilya** [comment]
I will try to fix it

**Comment by snuyanzin** [comment]
`x###` - I guess it might be an extension number

**Comment by panilya** [comment]
@snuyanzin The problem in `phone_number.yml` `phone_number.formats`, there are incorrect formats.
Also, I have a question, how to correctly run the test `PhoneNumberValidityFinderTest.testAllCellPhoneForLocale()`, I don't which region to take in `testAllCellPhoneForLocale` `String region = "?"` to test `phone_number.yml` in `resources/en/phone_number.yml`

**Comment by panilya** [comment]
Faker by default uses `Locale.ENGLISH`. Maybe this is obvious, but I can't understand In the `Locale` class, ENGLISH locale is written without defining region: `public static final Locale ENGLISH = createConstant("en", "");` . So, which `.yml` file does Datafaker use to generate when using the default locale? `resource/en.yml`?

**Comment by panilya** [comment]
@bodiam When generating phone numbers using Faker without specifying `Locale`, Faker uses `phone_number.yml` with not accurate formats but the most interesting thing is that `phone_number.yml` and `en-US.yml` `phone_number.formats` are both USA phone number formats, but `phone_number.formats` in `en-US.yml` has error count = 0 and `phone_number.yml` is incorrect. I'd like to know what to do. Copy formats from `en-US.yml` to `phone_number.yml`? What do you think?

**Comment by bodiam** [comment]
Good find. I have no issue if you want to copy them from en-US to phone_number, though it's a little strange we have two files for this. I  assumed it would use en-US by default.
