### ISSUE TITLE
Java 8 compatibility of 1.5.0

### ISSUE THREAD

**Issue by matrei** [datafaker-net/datafaker#283]
**Describe the bug**
Using datafaker 1.5.0 with java 8 throws java.lang.UnsupportedClassVersionError: net/datafaker/Faker has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**To Reproduce**
Use net.datafaker:datafaker:1.5.0 with Java 8

**Expected behavior**
That the library can be used with Java 8 as that is stated on the Readme: This library is a modern port of [java-faker](https://github.com/DiUS/java-faker), built on Java 8, with up to date libraries and several newly added Fake Generators.

**Versions:**
 - OS: Linux
 - JDK 1.8
 - Faker Version: 1.5.0

**Additional context**
Maybe release a 1.5.1 version that is compiled with target Java 8.

**Comment by bodiam** [comment]
I think that's my bad, I probably released it locally from a Java 11 machine instead of using the github action. 

Thanks for reporting it, I'll address it soon.

**Comment by AddisonSnyder** [comment]
Also in need of that compatibility. Thanks for bringing it up @matrei

**Comment by bodiam** [comment]
Can you please try the 1.6.0-SNAPSHOT version, and let me know if that one is 1.8 compatible? (It should be)

**Comment by matrei** [comment]
I have now tested 1.6.0-SNAPSHOT and this version is 1.8 compatible.

**Comment by bodiam** [comment]
Thanks for testing. Normally I release the versions through github actions, but for 1.5 I released it from my local machine using the maven release plugin, but I think I used 11 by accident. Thanks for testing it!

**Comment by bodiam** [comment]
It should be fixed now, please use version 1.6.0, released today.
