### ISSUE TITLE
Locale "ar" - Generating Male FullName with Female Title and Vice Versa. 

### ISSUE THREAD

**Issue by hashimati** [datafaker-net/datafaker#30]
**Describe the bug**
Using "Locale("ar") to generate a fake full name, the generated male full name is associated with the female's title and vice versa.  

**To Reproduce**
```java
Faker fake = new Faker(new Locale("ar")); 
String fullName = fake.name().fullName(); 
```
**Expected behavior**

Female Example 1: 
Generated By FakeData : **السيّد** الخنساء زايد
With Correct Title: **السيّدة** الخنساء زايد

Female Example 2: 
Generated By FakeData: **الدكتور** فاطمة العديني
With Correct Title: **الدكتورة** فاطمة العديني

Male Example: 
Generated By FakeData : **السيّدة** عبدالعزيز بامحفوظ
With Correct Title: **السيّد** عبدالعزيز بامحفوظ

**Versions:**
 - OS: Windows 10
 - JDK: Java 17
 - Faker Version 1.1.0

**Comment by bodiam** [comment]
Hi @hashimati , thanks for reporting this. I've checked the source, and I see this: الدكتور

If my understanding is correct, this translates to Doctor. Is this a female or male title? Or can it be used for both?

Also, the firstnames are like this:

first_name: [عمر, محمّد, أحمد, عبدالله, عبدالرحمن, عبدالرزّاق, عبدالصّمد, نوّاف , خالد, البراء, إسراء, فاطمة, مريم, سميّة, فوز, فوزية, خديجة, الخنساء, حنان, عبير, أنس, مالك, أبيّ, وائل, مشعل, وائل, أبو بكر, عمرو, عمّار, غدير, غادة, إيمان, نوف, خديجة, عائشة, عاتكة, شمس, دانة, ألهام, فهد, نايف, عبدالعزيز, عبدالمحسن, مهنّد, مصعب, حاتم, عبدالوهّاب, همّام, حمزة, خولة, خلود, ابتهال, أمة الله, صفية, خالدة, رابعة, بدوية, رؤية, سندس]

Are these mixed firstnames? I'm thinking of splitting them in male and female firstnames, just like what has been done in Ruby Faker:


      male_first_name: [حمزة, خالد, نوّاف, عبدالصّمد, عبدالرزّاق, عبدالرحمن, عبدالله, أحمد, محمّد, عمر, نايف, فهد, عمّار, عمرو, أبو بكر, وائل, وائل, مالك, عبدالوهّاب, حاتم, مصعب, مهنّد, عبدالمحسن, عبدالعزيز]
      female_first_name: [عبير, حنان, الخنساء, خديجة, فوزية, فوز, سميّة, مريم, فاطمة, إسراء, ألهام, دانة, شمس, عائشة, خديجة, نوف, إيمان, غادة, غدير, سندس, رؤية, بدوية, رابعة, خالدة, صفية, ابتهال, خلود, خولة]
    
But I'd like to understand if this correct.

Thanks, Erik

**Comment by bodiam** [comment]
```
مصعب النابلسي
إسراء خيّاط
خديجة عيد
الدكتور محمّد الأمير
محمّد القادريّ
محمّد العديني
السيّد خالد العديني
فوز شوكت
فهد الصنعاني
محمّد رشدي
فهد العطّاس
الدكتور مصعب حسني
خلود القادريّ
مالك شلبي
عبدالرحمن الصعيدي
عبدالرحمن شاهين
عبدالمحسن أبو خالد
فهد مجدي
عبدالله العطّاس
الخنساء إمام
مهنّد الدوعني
السيّد مصعب النابلسي
مهنّد كوسة
بدوية الغامدي
عمّار حلمي
```

These are the names generated after the fix. With some help from Google Translate, they look to me, can you confirm?

**Comment by bodiam** [comment]
I've published this fix in 1.2.0-SNAPSHOT (see http://www.datafaker.net/getting-started/#snapshot-versions). Could you please give it a try?

**Comment by hashimati** [comment]
Hi @bodiam, 

Sorry for the late reply, because I was traveling. Usually, the female's title ends with the letter "ة." So, **الدكتور** is used for males and **الدكتورة** for females. 

In the generated name after fixed, there is one incorrect for a female name which is: 
**الدكتور** خالدة الغزاوي
It should be **الدكتورة** خالدة الغزاوي


Regarding the mentioned list of First_name, they mixed males & females. And, the males & females lists of Ruby faker are correct. 
first_name: [عمر, محمّد, أحمد, عبدالله, عبدالرحمن, عبدالرزّاق, عبدالصّمد, نوّاف , خالد, البراء, إسراء, فاطمة, مريم, سميّة, فوز, فوزية, خديجة, الخنساء, حنان, عبير, أنس, مالك, أبيّ, وائل, مشعل, وائل, أبو بكر, عمرو, عمّار, غدير, غادة, إيمان, نوف, خديجة, عائشة, عاتكة, شمس, دانة, ألهام, فهد, نايف, عبدالعزيز, عبدالمحسن, مهنّد, مصعب, حاتم, عبدالوهّاب, همّام, حمزة, خولة, خلود, ابتهال, أمة الله, صفية, خالدة, رابعة, بدوية, رؤية, سندس]



Thanks, Ahmed

**Comment by bodiam** [comment]
Thank you for the extensive writeup,  appreciate it. Just one final  question:

الدكتورة

Does this apply to both medical as academic doctors? The context this title is about is the academic one, just want to make sure that these are handled the same as the medical doctors.

**Comment by hashimati** [comment]
You are welcome!

Yes, it does apply to both medical and academic.

**Comment by bodiam** [comment]
Thanks, I'll address this tonight! Thanks again for the feedback and quick communication, that helps a lot!

**Comment by bodiam** [comment]
Hi @hashimati , I'm going to assume this issue is fixed for now, and will be part of the 1.2.0 release. Thanks again for reporting it!

**Comment by hashimati** [comment]
Hi @bodiam, I am extremely busy since two todays and I didn't a chance to check. We can assume that it is closed. I'll check it this weekend and I'll let you know.

Have a nice day
Ahmed

**Comment by bodiam** [comment]
No worries at all! If I made a mistake or something is missing, just let me know and I'll fix it!

**Comment by hashimati** [comment]
I just tried it. It's perfect.

Best Regards, 
Ahmed
