### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by snuyanzin** [datafaker-net/datafaker#320]
Any objections regarding following a kind of cutting edge of the base branch naming?

**Comment by epragtbeamtree** [comment]
What's the value of renaming the branch(es)?

**Comment by snuyanzin** [comment]
since more and more repos are renaming master to main,  over time 'master'
will start to become anachronism. 
it's better to have a bunch of repos with same name of base branch

**Comment by bodiam** [comment]
I have no opinion on this, but if you think it's a good idea, go for it.

**Comment by snuyanzin** [comment]
ok, done
please do this locally
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

cc @bodiam @panilya

**Comment by snuyanzin** [comment]
https://github.com/datafaker-net/datafaker/commit/65a5152cf449a5028412d9ad732db275309b0b85
