### ISSUE TITLE
Apply spotless autoformating with google-java-format

### ISSUE THREAD

**Issue by snuyanzin** [datafaker-net/datafaker#330]
**Is your feature request related to a problem? Please describe.**
This is a follow-up task for https://github.com/datafaker-net/datafaker/pull/329
The issue is that if we blindlessly apply spotless google-java-format then formatting required by spotless will differ from formatting done by IDE.

**Describe the solution you'd like**
The idea is to setup google-java-format plugin for IntellijIdea, Eclipse as mentioned at https://github.com/google/google-java-format
and make it used by default for the project.
Then we could enable autoformatting for spotless since both spotless and IDE will produce same formatting

WDYT?

// cc @bodiam @yuokada

**Comment by bodiam** [comment]
This is really not an issue affecting me, and as such, I prefer not to spend time on this if that's okay with you.

**Comment by bodiam** [comment]
What do you want to do with this @snuyanzin ?
