### ISSUE TITLE
Introduce a way to specify the format of the generated phone numbers

### ISSUE THREAD

**Issue by panilya** [datafaker-net/datafaker#424]
To illustrate what I mean:

Somehow give the ability to choose a format of a phone number, for example among these: 
```
(###) ###-####
### ### ####
###-###-####
##########
+#-###-###-####
+# (###) ###-####
```

**Comment by snuyanzin** [comment]
why already existing functionality does not help?
e.g. numerify https://www.datafaker.net/documentation/expressions/#numerify

**Comment by panilya** [comment]
For example, if you want to generate a phone number in `en-US` locale using `numerify`, you will get a lot of incorrect phone numbers.there will be incorrect area codes, etc.

**Comment by epragtbeamtree** [comment]
Ah, so you want to generate a valid phone number, and when the locale provides multiple formats, only choose one of them? I'm not really sure how to do that. For example, the US one might have 8 different formats, the Australian one 4, and the Dutch locale 2. How would you even know which format you want? 

Am I understanding this correctly?

I think the best thing you could do is generate numbers, remove all the formatting, and then apply the format you want to see (I'm not sure if that's a task for Datafaker though).

**Comment by snuyanzin** [comment]
The problem of current solution is that it generates a string instead of e.g. a `PhoneNumber` object. 
The solution is a generation of a real `PhoneNumber` object and then it is possible to use embedded functionality of libphonenumber like https://github.com/google/libphonenumber#quick-examples

**Comment by snuyanzin** [comment]
Or another way with current approach
```java
String swissNumberStr = faker.generatewhateverphonenumber;// Produces e.g. "+41 44 668 18 00"
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
try {
  PhoneNumber swissNumberProto = phoneUtil.parse(swissNumberStr, "CH");
  // Produces "+41 44 668 18 00"
  System.out.println(phoneUtil.format(swissNumberProto, PhoneNumberFormat.INTERNATIONAL));
  // Produces "044 668 18 00"
  System.out.println(phoneUtil.format(swissNumberProto, PhoneNumberFormat.NATIONAL));
  // Produces "+41446681800"
  System.out.println(phoneUtil.format(swissNumberProto, PhoneNumberFormat.E164));
} catch (NumberParseException e) {
  System.err.println("NumberParseException was thrown: " + e.toString());
}
```

**Comment by epragtbeamtree** [comment]
Yes, but you can also do stuff like:

```kotlin
var number = faker.generateAwesomeNumber("US")
var cleaned = util.stripEverythingWhichIsntANumber(number)

// Format it however you like
println("(" + cleaned.substring(0,3) + ") " + cleaned.substring(3,6) + " " + cleaned.substring(6))
```

Or something like that.

**Comment by panilya** [comment]
Now, I understood, as @epragtbeamtree mentioned, it's really a task not for Datafaker. 

An approach by @snuyanzin actually suits this task

**Comment by epragtbeamtree** [comment]
Depends what you want to generate. The PhoneNumberLib is great, and def something you should use for more standardized ways of formatting. the `libphonenumber` library [only supports a few different formats](https://www.javadoc.io/doc/com.googlecode.libphonenumber/libphonenumber/8.7.0/com/google/i18n/phonenumbers/PhoneNumberUtil.PhoneNumberFormat.html) though, so if you want to go crazy with parenthesis, I don't think libphonennumber is enough.

Back to the question though: what are you trying to accomplish?

**Comment by panilya** [comment]
How about introducing some util or service, that will wrap logic of formatting to different formats

**Comment by snuyanzin** [comment]
I would say it's better to contribute to `libphonenumber`. 
Otherwise datafaker will drastically grow in terms of `utils.format.whatever` just because there is not only phone numbers but lots of different things which potentially could be formatted differently depending on locale and may be something else

**Comment by epragtbeamtree** [comment]
How about you make that a feature of your web version first, and once you know how it should look, we can consider it here? I think some external library/feature is better, but I like to be convinced by code, so if you have an good util class which can support multiple locales etc, then we could consider including it (or, we could even make a `datafaker-formatting` artifact, if that makes sense)

**Comment by epragtbeamtree** [comment]
@panilya you saw this one right? https://www.mockaroo.com/
