### ISSUE TITLE
How about we drop Java 8?

### ISSUE THREAD

**Issue by bodiam** [datafaker-net/datafaker#428]
Java 8 is getting quite old these days, and I'm not sure if keeping Java 8 as a baseline is going to be helpful in the long run.

My proposal is to move to Java 11 instead for the next year(s) or so, and maybe call it Datafaker 2.0 to make the distinction. People on Java 8 can still use Datafaker 1.x, but the main version of Datafaker would have Java 11 as a minimum.

Thoughts, concerns?

**Comment by snuyanzin** [comment]
I'm kind of +0 to this: no objections however do no see benefits... It's not clear what besides java11 syntax sugar could be used within the project....

**Comment by bodiam** [comment]
Yeah, agreed. It was triggered by my need for a decent http client, but I think I'll work around it by creating a new Java 11 repo with slightly different dependencies.

**Comment by epragtbeamtree** [comment]
Let's not drop Java 8 yet until we have a really good reason.
