### ISSUE TITLE
Support extensible model to register custom external faker service

### ISSUE THREAD

**Issue by dnicholas2001** [datafaker-net/datafaker#45]
Support the ability to create a new faker service externally and provide support from within Faker class to use the external faker data.

The alternative is to make a PR to this code repo, however, what if the data in the faker service is specific to an industry that may not apply to everyone. 

Maybe consider an interface and service loader approach in which subtypes of the interface are registered with the Faker service using the Java ServiceLoader pattern.

**Comment by bodiam** [comment]
Hi @dnicholas2001 , would you be willing to maybe implement or prototype a feature like this?

I'm very open to the idea, and I thought that creating a provider and giving it a faker in the constructor would already bring you quite far, except for the loading of the yml files. 

However, I think in general it wouldn't be too bad to replace that whole list of yml files to the individual providers themselves.

**Comment by bodiam** [comment]
Ideally, it would support the (future) idea of being able to split the faker into separate modules. For example, I can imagine an Address faker is more interesting to most than something like an IT crowd faker. But I don't want to overcomplicate things, but just an idea.

**Comment by dnicholas2001** [comment]
Would be happy to contribute! The existing design is using concrete classes, so it would be a challenge to get the Faker class to have knowledge of an external service. For example, how would it know to call `faker.spaceForce().nextRocketName()`, for example.

Unless, maybe, there was an interface to club together common categories of data. Maybe `IProvideDataForTest` and each interface method could provide some level of data. But the data provided is specific to the industry, so `nextRocketName()` applies to space, but `nextVehicleName()` applies to automotive.

Maybe there's a pattern that is common to the existing domains represented by the `yml` files? Will look into this

**Comment by bodiam** [comment]
You're right that the Faker api complicates things. 

The api I had in mind, but I'm not 100% sure, was to do either:

PlantProvider(new Faker()).flower()

Or:

public <T> provider(Class<T> provider) 

So that you can do:

new Faker().provider(PlantProvider.class).flower()

I don't know how the interface approach could work, since like you said, there's not really an overlap between the different domains, so not using interfaces but using generics could maybe be a better approach. I haven't tested it yet though, so it's just ideas.

**Comment by dnicholas2001** [comment]
I agree, I like the idea of using Generics!

**Comment by bodiam** [comment]
```
    public <T> T provider(Class<T> provider) {
        return null;
    }
    
    void test() {
         new Faker().provider(Avatar.class).image();
    }
```

The above seems to work (or at least compile), so something like this might be an option. If you'd mix this with an SPI (if you need it really, maybe just passing the class is good enough), that could be a good starting point. 

It doesn't have a to be perfect, but maybe just a starting point, and we'll work out something,

**Comment by snuyanzin** [comment]
It also could be done by extending `Faker` e.g. there is a custom rocket name generator
```java
    public static class Rocket<T extends Faker> {
        private final T faker;

        public Rocket(T faker) {
            this.faker = faker;
        }

        public String name() {
            String[] names = new String[] {"Appollo", "Soyuz", "Vostok", "Voskhod", "Progress", "Falcon", "Gemini", "Mercury"};
            return names[faker.random().nextInt(names.length)];
        }
    }
```

Now need to extend `Faker` like 
```java
    public class MyFaker extends Faker {
        public Rocket rocket() {
            return getProvider(Rocket.class, () -> new Rocket<>(this));
        }
    }
```

and finally it could be used with names from custom
```java
    @Test
    public void myRocketTest() {
        new MyFaker().rocket().name();
    }
```

P.S. currently this could be done with usage of master's version...
datafaker 1.1.0 does not support this

**Comment by dnicholas2001** [comment]
@snuyanzin Many thanks for sharing. In your example, would you recommend we maintain the sample data within the Java file, or is there a way you think we can reuse the functionality within `Faker` to marshal the sample data from the `yml` files?

**Comment by snuyanzin** [comment]
Current version does not support usage of `Faker`s  functionality for marshalling data from custom `yml`.
In theory it could be improved

**Comment by snuyanzin** [comment]
@dnicholas2001 I have a PR supporting adding files with custom data, you might want to have a look at it
https://github.com/datafaker-net/datafaker/pull/49
Also there is an example inside tests

**Comment by bodiam** [comment]
What do you think, can this issue be closed?

**Comment by snuyanzin** [comment]
The pr was merged, there are several examples within a test _src/test/java/net/datafaker/CustomFakerTest.java_ custom fakers could be used

@dnicholas2001 could you please tell if there is anything missing?

**Comment by bodiam** [comment]
@dnicholas2001 it's already released as a snapshot, so if you want to try that one out, that would be great. The actual 1.2.0 release is planned for ~10 days.

**Comment by dnicholas2001** [comment]
@bodiam  , didn't know that, great to hear! Will definitely try it out; thanks for sharing!
