### ISSUE TITLE
The edit link in public docs pages get 404, going to master not main

### ISSUE THREAD

**Issue by carehart** [datafaker-net/datafaker#450]
**Describe the bug**
If you visit a page like https://www.datafaker.net/documentation/usage/, and try to use the edit button (such as to suggest a typo), that edit button's link goes to:
 https://github.com/datafaker-net/datafaker/edit/master/docs/documentation/usage.md

which gets a 404. That should instead be main, not master, so:
 https://github.com/datafaker-net/datafaker/blob/main/docs/documentation/usage.md

I tried to find any reference for that in the code base here (to suggest a pr) but could not. Perhaps some process outside this repo is what controls creating the publication of the docs on the datafaker.net site.

I do understand why and how this problem came to be, and how this could easily slip through the cracks. I just share it to help you help others... to help you. :-) 

I can tell you that on a mobile, it wasn't so easy to connect the dots of what was happening. Other casual readers who, on mobile, might have tripped on this may not have had the time/gumption to dig in, let alone report the issue.

Hope it's a really simple fix for you to do. Thanks for the efforts on the project. I just learned of it today.

**Comment by bodiam** [comment]
Hi @carehart , you're the second one to mention this this week, so time to fix! 

Fixed it here: https://github.com/datafaker-net/datafaker/pull/452

Thanks again for mentioning/reminding me!

**Comment by bodiam** [comment]
Deployed now, all links should work (tested a few)!

**Comment by carehart** [comment]
Thanks. I'm not seeing it reflected on the site, even with cache clearing. Will that take some additional time? Just asking for any following along or who may find this later. 

Also, about it being the second request about it this week, I'll note that I'd checked if any issues existed (open or closed), but maybe you mean someone reached out to you directly. Anyway, thanks for addressing it. :-)

**Comment by bodiam** [comment]
Yeah, it took a while for me to be updated to, and had to do some shift refreshes.

You're correct that there wasn't an issue for this. I think it came up in a conversation, and I should have fixed it immediately. I'll check on mobile too to see if it's really fixed.

**Comment by bodiam** [comment]
Seems to be working on mobile as well. Please let me know if it doesn't work for you, might be caused by pointing to the main repo or so if it fails.
