### ISSUE TITLE
related fake data needed

### ISSUE THREAD

**Issue by ruhuansanmei** [datafaker-net/datafaker#463]
I generate some data with this:
    Address address =  faker.address();
    System.out.println(address.country());
    System.out.println(address.city());
    System.out.println(address.streetAddress());
    System.out.println(address.longitude());
    System.out.println(address.latitude());
The country and the city are not related. Can I get them related?
![git](https://user-images.githubusercontent.com/17924820/197317553-a3b9706c-9ed2-4fc9-89f1-daa83ec2845b.png)

**Comment by bodiam** [comment]
Hi, this is not a feature we support yet, but I believe jFairy has the concept of profiles which might help. 

We would like to have a concept like this though, though some of it might get hard, for example, we don't know the coordinates of a country or city, and depending on your use case, that might be a feature which you'd like to see related too.

We're open to suggestions, PRs, etc though, so if you have some ideas on how to make this work well, do let us know!

**Comment by snuyanzin** [comment]
> The country and the city are not related. Can I get them related?

you can still implement your custom provider for that task
More info about that here https://www.datafaker.net/documentation/custom-providers/

**Comment by ruhuansanmei** [comment]
Thank you!
