### ISSUE TITLE
Proposal to use ThreadLocalRandom instead of Random 

### ISSUE THREAD

**Issue by NarekDW** [datafaker-net/datafaker#562]
Hi guys, do you think does it worth to consider using `ThreadLocalRandom` instead of `Random` class?
Does it worth to perform some benchmarks regarding this and check performance results?

## Problem
`ThreadLocalRandom` theoretically should work faster than `Random` class.

## Solution
Use `ThreadLocalRandom` instead of `Random` in `RandomService` class.

**Comment by snuyanzin** [comment]
How are you going to support ability to run code with the same seed e.g. like in this test
https://github.com/datafaker-net/datafaker/blob/9e6308b67022c91c31f4218f02021e7cf56e1eea/src/test/java/net/datafaker/FakerTest.java#L239-L248

**Comment by snuyanzin** [comment]
At the same time there could be applied another optimization: just reduce number of calls to `Random#nextWhatever` by usage of `nextBytes`
here it is an example of such optimization already applied for text generation and it gives about 3x times speed up
https://github.com/datafaker-net/datafaker/pull/530

**Comment by NarekDW** [comment]
> How are you going to support ability to run code with the same seed? e.g. like in this test
> 
> https://github.com/datafaker-net/datafaker/blob/9e6308b67022c91c31f4218f02021e7cf56e1eea/src/test/java/net/datafaker/FakerTest.java#L239-L248

Actually, I don't know. 
Is it fine if we get rid of such kind of tests?
Otherwise, the only solution I see here - is to support 2 variables - 
1. Random (for backward compatibility) and mark it as deprecated
2. ThreadLocalRandom (if Random variable is not defined)

**Comment by bodiam** [comment]
@NarekDW no, it's not fine too get rid of tests like this, but sure, you could try use ThreadLocalRandom and do some performance tests, it would make the conversation a bit easier when we know if it's 10% faster or 100x faster.

**Comment by snuyanzin** [comment]
>Is it fine if we get rid of such kind of tests?

no that's not fine. That is one of the features (reproducible results) and as far as i know there are users who use it .

What is the problem to init your faker as
```java
var faker = new Faker(ThreadLocalRandom.current());
```
since it allows to transmit anything extending `Random`

**Comment by NarekDW** [comment]
> > Is it fine if we get rid of such kind of tests?
> 
> no that's not fine. That is one of the features (reproducible results) and as far as i know there are users who use it .
> 
> What is the problem to init your faker as
> 
> ```java
> var faker = new Faker(ThreadLocalRandom.current());
> ```
> 
> since it allows to transmit anything extending `Random`?

Yep, as ThreadLocalRandom extends Random, this looks as a best solution.

**Comment by snuyanzin** [comment]
By the way 
some result of tests `Random` vs `ThreadLocalRandom`
`Random`
```
Benchmark                              Mode  Cnt      Score      Error   Units
DatafakerSimpleMethods.firstname      thrpt   10   4519.530 ±  175.167  ops/ms
DatafakerSimpleMethods.fullname       thrpt   10   2102.625 ±  152.091  ops/ms
DatafakerSimpleMethods.numberBetween  thrpt   10  40265.386 ± 7202.939  ops/ms
DatafakerSimpleMethods.streetAddress  thrpt   10   1308.444 ±   32.046  ops/ms
```

`ThreadLocalRandom`
```
Benchmark                              Mode  Cnt      Score      Error   Units
DatafakerSimpleMethods.firstname      thrpt   10   4350.799 ±  302.775  ops/ms
DatafakerSimpleMethods.fullname       thrpt   10   2058.009 ±  105.322  ops/ms
DatafakerSimpleMethods.numberBetween  thrpt   10  54261.229 ± 2555.748  ops/ms
DatafakerSimpleMethods.streetAddress  thrpt   10   1307.464 ±   10.895  ops/ms
```

It looks like `ThreadLocalRandom` gives some improvement only for cases of direct calls of `Random` methods like numbers and no improvement for any other provider

**Comment by NarekDW** [comment]
Closing the issue

**Comment by NarekDW** [comment]
@snuyanzin by the way, I compared Random vs ThreadLocalRandom directly, like this:
```java
Random random = new Random();
ThreadLocalRandom threadLocalRandom = ThreadLocalRandom.current();

@Benchmark
public void nextIntRandom(Blackhole bh) {
    for (int i = 0; i < 1_000_000; i++)
        bh.consume(random.nextInt());
}

@Benchmark
public void nextIntThreadLocalRandom(Blackhole bh) {
    for (int i = 0; i < 1_000_000; i++)
        bh.consume(threadLocalRandom.nextInt());
}
```

and got such results:
```java
Benchmark                                           Mode  Cnt    Score   Error  Units
RandomGeneratorBenchmark.nextIntRandom             thrpt    5  106.481 ± 0.587  ops/s
RandomGeneratorBenchmark.nextIntThreadLocalRandom  thrpt    5  329.274 ± 0.538  ops/s
```

ThreadLocalRandom is 3x times faster here.

**Comment by snuyanzin** [comment]
from user's point of view it would make sense to compare end to end cases.
It means that for datafaker's users it means nothing because it does not reflect the whole duration of the e2e opeartion. Datafaker's user could invoke nextNumber or numberbetween where it's used.

**Comment by NarekDW** [comment]
I think it could be considered as an end to end case, because, as a user, I can use all that methods from `RandomService` directly, as it is public, and I can create an instance of that class:
```java
    // From BaseFaker
    public RandomService random() {
        return this.context.getRandomService();
    }
```

**Comment by snuyanzin** [comment]
it would be a very strange usage: use of datafaker in order to call only Random's methods...
In this case i would suggest to use Random only instead of datafaker and then no need for datafaker initialization overhead since it is not used
