### ISSUE TITLE
Improve generating a String from given regexp 

### ISSUE THREAD

**Issue by mat-mik** [datafaker-net/datafaker#568]
**Is your feature request related to a problem? Please describe.**
Sometimes we use regexp with strict pattern, like `^\\d{5}$` and we can't use those patterns in `regexify` method because it copies `^`,  `$` characters to newly created String, example:
```java
String regexp ="^\\d{5}$";
System.out.println("faker.regexify(regexp) = " + faker.regexify(regexp)); // ^67213$
```

**Describe the solution you'd like**
Given example generates a string `67213` instead of `^67213$`

**Additional context**
I can see that datafaker delegates work to mifmif/Generex but it seems that library is no longer maintained, so it may require additional work like changing library or writing custom solution.

**Comment by bodiam** [comment]
I'm not sure what to do with this. Generex hasn't been maintained for a long time, and I'm not sure if Datafaker should fix those issues. Ideally, it would be fixed downstream, and have others benefit from this. I don't think it  would be great to come up with all kinds of hacks to remedy this. 

If you know a better regex library, happy to drop this one and replace by a better one, but I haven't found one myself.

**Comment by snuyanzin** [comment]
I wonder what is the reason to pass such regex?
anyway why can't be handled in custom code e.g.
```java
String regexp ="^\\d{5}$";
regexp = regexp.charAt(0) == '^' ? regexp.substring(1): regexp;
regexp = regexp.charAt(regexp.length() - 1) == '$' ? regexp.substring(0, regexp.length() - 1): regexp;
System.out.println("faker.regexify(regexp) = " + faker.regexify(regexp)); // 67213
```
or could be extracted in a separate method

**Comment by mat-mik** [comment]
Thanks for your answers! Really appreciate that.

@snuyanzin, yes that can be easily handled on our side (and it is, we create `String` without those characters which is passed to `Faker` and to `Pattern` which is surrounded by those chars). 

So - I have to agree that - this task/request is more of checking if we could delegate that work to the library rather than doing it manually, because that's super verbose. And the reason for that is that for instance patterns with groups work perfectly:
```java
String regexp = "\\d{4}(\\d)";
System.out.println("faker.regexify(regexp) = " + faker.regexify(regexp)) // 67213
```

@bodiam, fully agree that in the best scenario it should be fixed in other library. And I wasn't thinking about any hacks to support that request, but rather changing dependency (but I couldn't find any better library) or creating new solution to generate regexps. But I'm not aware how many requests/bugs you experience regarding `regexify` method. If none, than I think we can close that ticket immediately.

**Comment by bodiam** [comment]
I'm sorry, but I think this beyond the scope of this project. I'm happy to introduce a better regex library if there's one, or if this can be fixed in the Generex library, even better.
