### ISSUE TITLE
Change logo in Maven Central

### ISSUE THREAD

**Issue by panilya** [datafaker-net/datafaker#587]
The logo in `datafaker-net` organization and Maven Central is different.

https://mvnrepository.com/artifact/net.datafaker/datafaker/1.7.0

**Comment by bodiam** [comment]
I don't think this is Maven Central, this is a mvn repository thing, not sure why they don't update to the new logo.

**Comment by jonathanlermitage** [comment]
I confirm, Sonatype runs Maven Central repository and [index](https://search.maven.org/artifact/net.datafaker/datafaker/1.7.0/jar).  
mvnrepository.com seems to be an independent index.

**Comment by bodiam** [comment]
Don't think we can change the logo. I sent them a message on Twitter, but no response.
