### ISSUE TITLE
Use expressions with custom faker and provider

### ISSUE THREAD

**Issue by rjrudin** [datafaker-net/datafaker#593]
**Is your feature request related to a problem? Please describe.**

First off - great product, I tried it out for a fake data generation tool for [MarkLogic](https://www.marklogic.com/) and it couldn't have been easier to use. 

Next - I've been following the example shown in [CustomFakerTest](https://github.com/datafaker-net/datafaker/blob/main/src/test/java/net/datafaker/providers/base/CustomFakerTest.java) for my use case of creating a `MarkLogicFaker` with methods that can generate fake data based on data already in a MarkLogic database. Everything is working well, CustomFakerTest is a really nice example. So my prototype looks roughly like this:

```
MarkLogicFaker faker = new MarkLogicFaker(...);
System.out.println(faker.markLogic().helloWorld());
```

My problem is that in the tool I wrote that uses datafaker, I'm using `faker.expression`, and so what I want to do is this:

```
MarkLogicFaker faker = new MarkLogicFaker(...);
System.out.println(faker.expression("#{markLogic.helloWorld}");
```

When I do that, I get the following error:

```
Unable to resolve #{markLogic.hello} directive for FakerContext FakerContext{locale2localesChain={en=[en]}, locale=en, randomService=net.datafaker.service.RandomService@29ca3d04}.
	at net.datafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:512)
	at net.datafaker.service.FakeValuesService.expression(FakeValuesService.java:400)
	at net.datafaker.providers.base.BaseFaker.expression(BaseFaker.java:403)
```

**Describe the solution you'd like**

I'm hoping there's something I'm missing in how I'm setting up my custom faker and provider. My prototype is doing exactly what's shown in CustomFakerTest, and hopefully there's just something else I need to do in order for expressions to work on a custom provider? 

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by snuyanzin** [comment]
Am I right that based on `System.out.println(faker.markLogic.helloWorld());` it seems `markLogic` is a field?
Fields are not supported. Only methods

**Comment by rjrudin** [comment]
My apologies, I had a typo in the issue - I'll fix that, but this is a better example:

```
MarkLogicFaker faker = new MarkLogicFaker(client);
System.out.println(faker.name().firstName()); //works
System.out.println(faker.expression("#{name.firstName}")); // works
System.out.println(faker.markLogic().hello()); // works
System.out.println(faker.expression("#{markLogic.hello}")); // fails
```

The `MarkLogicFaker` class declares a method using `MarkLogicProvider` in a similar fashion to what's shown in CustomFakerTest:

```
public MarkLogicFaker(DatabaseClient client) {
    this.client = client;
}

public MarkLogicProvider markLogic() {
    return getProvider(MarkLogicProvider.class, faker -> new MarkLogicProvider(faker, this.client));
}
```

My guess is that I need to do something in terms of overriding `getContext()` in BaseFaker, as I'm guessing that the expression is being resolved against a BaseFaker instance and not my MarkLogicFaker instance, but that's just a guess (that's what I'm poking around at right now).

**Comment by rjrudin** [comment]
I'm thinking I can get this working, as I just verified that faker.expression works fine with the example in CustomFakerTest:

```
MyCustomFaker faker = new MyCustomFaker();
System.out.println(faker.insect().nextInsectName());
System.out.println(faker.expression("#{insect.nextInsectName}"));
```

**Comment by rjrudin** [comment]
Yup - user error on my part, I had made the provider a private static class instead of public - sorry for the confusion!
