### ISSUE TITLE
Expand SV local names

### ISSUE THREAD

**Issue by robosoul** [datafaker-net/datafaker#635]
**Is your feature request related to a problem? Please describe.**
Current sv list of first names (male and female) as well as last names is incomplete.
```
% grep 'female_first_name' sv.yml | grep -o '[[][^]]*]' | sed 's/[[]//; s/[]]//; s/, /,/g' | tr ',' '\n' | wc -l
      13

% grep '[^a-z]male_first_name' sv.yml | grep -o '[[][^]]*]' | sed 's/[[]//; s/[]]//; s/, /,/g' | tr ',' '\n' | wc -l
      14

% grep 'last_name' sv.yml | grep -o '[[][^]]*]' | sed 's/[[]//; s/[]]//; s/, /,/g' | tr ',' '\n' | wc -l
      13
```

List of Swedish first/last names on wiki is more complete, around 200 first names, and 600 last names.

**Describe the solution you'd like**
Expand the `female_first_name`, `male_first_name` and `last_name` collections for sv locale.

**Comment by snuyanzin** [comment]
thanks for the issue
however we are all volunteers here and there is none of maintainers covering all the locales.
So PR and help would be more fruitful.

**Comment by robosoul** [comment]
Hi @snuyanzin - Thanks for your reply. I am aware, I contributed to original java faker project, and I plan to support locales as I go (for my needs). I just thought it's better to have a ticket open before starting with the work :) PR coming in a few days ;) Cheers, Luka

**Comment by snuyanzin** [comment]
ok, great
looking forward for the PRs

**Comment by bodiam** [comment]
Hi, I commented the same at the other issue before I saw this issue. Thanks for reporting it, and happy to accept any PRs related to these Locales!

**Comment by robosoul** [comment]
All good guys, I'm use to opening ticket first, and then start working. Sorry for the confusion ;)

**Comment by robosoul** [comment]
@bodiam and @snuyanzin - here's the PR: https://github.com/datafaker-net/datafaker/pull/638
