### ISSUE TITLE
Expand DK local names

### ISSUE THREAD

**Issue by robosoul** [datafaker-net/datafaker#637]
Is your feature request related to a problem? Please describe.
There is limited first/last name collections for locale `dk`.

```
% grep 'last_name' src/main/resources/da-DK.yml | grep -o '[[][^]]*]' | sed 's/[[]//; s/[]]//; s/, /,/g' | tr ',' '\n' | wc -l            
      10
% grep 'first_name' src/main/resources/da-DK.yml | grep -o '[[][^]]*]' | sed 's/[[]//; s/[]]//; s/, /,/g' | tr ',' '\n' | wc -l 
      20
```

Describe the solution you'd like
Expand DK first/last name using following:

- https://en.wikipedia.org/wiki/Category:Danish_masculine_given_names
- https://en.wikipedia.org/wiki/Category:Danish-language_surnames
- https://en.wikipedia.org/wiki/Category:Danish_feminine_given_names

**Describe alternatives you've considered**
Created local file that I plan to move to this repo.

**Comment by bodiam** [comment]
Hi! There are no names for many locales. If you want to do a PR for them to add them, we would be happy to accept such contributions!

**Comment by robosoul** [comment]
@bodiam - here's the PR: https://github.com/datafaker-net/datafaker/pull/640
