### ISSUE TITLE
Fake data based on JSON schema

### ISSUE THREAD

**Issue by andrinmeier** [datafaker-net/datafaker#646]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Input: JSON schema (https://json-schema.org/), output: valid JSON with fake data based on said schema.

**Describe alternatives you've considered**
Generating a fake JSON by manually specifying the properties / values to generate. This is cumbersome if there many schema changes though.

**Additional context**
No additional context.

**Comment by bodiam** [comment]
Have a look at https://Schematix.net 

It's using Datafaker under the hood, and does something similar as what you're looking for perhaps.

**Comment by andrinmeier** [comment]
Thanks, yes that should work.
