### ISSUE TITLE
JsonTransformer::generate() change to support json array not one big doc that doesn't validate

### ISSUE THREAD

**Issue by mesketh** [datafaker-net/datafaker#651]
[JsonFormatter](https://github.com/datafaker-net/datafaker/blob/main/src/main/java/net/datafaker/transformations/JsonTransformer.java#L53) uses a comma to separate out each generated json document/record wrapped with a pair of `{}` which of course, doesn't validate _as is_ nor does it import to mongodb out of the box. Yes, yes I can replace the curlies with sq brackets but I just wonder how useful it is to emit this in the first place.

**Describe the solution you'd like**
To make it more useful e.g. to directly import into a mongo collection, can we add support for wrapping as a json array instead? This will then conveniently import into mongo (`mongoimport --jsonArray ... `).

**Comment by bodiam** [comment]
Hi @mesketh , I see no issue with such a change. Are you willing to contribute with a PR?

@snuyanzin Thoughts on this?

**Comment by snuyanzin** [comment]
IIRC BigQuery is ok with importing one-line JSON, so I guess should also keep current behavior.
Probably need kind of some configuration parameters and a builder to construct transformer.
Then different scenarios could be supported e.g. BigQuery, Mongo and etc.

**Comment by mesketh** [comment]
> IIRC BigQuery is ok with importing one-line JSON,
BQ seems to follow this [JSON Lines format](https://jsonlines.org/) which is 1:1 json obj per line. Not sure whether it ignores the "," currently emitted.
 > Probably need kind of some configuration parameters and a builder to construct transformer. Then different scenarios could be supported e.g. BigQuery, Mongo and etc.
Yep - I guess as a default I was suggesting something pretty ubiquitous like Mongo and something you can shove into a json validator and get a ✅ but, happy to get involved in a broader solution @snuyanzin @bodiam

**Comment by snuyanzin** [comment]
>BQ seems to follow this [JSON Lines format](https://jsonlines.org/) which is 1:1 json obj per line. Not sure whether it ignores the "," currently emitted.

need to double check it. I remember I tested it with the very first version of json generation in datafaker however I didn't do with the latest.
Anyway comma also could be configurable

@mesketh let me know if you want to contribute a PR here (in this case i will remove this issue from my task list and will participate only in review)

**Comment by mesketh** [comment]
> > BQ seems to follow this [JSON Lines format](https://jsonlines.org/) which is 1:1 json obj per line. Not sure whether it ignores the "," currently emitted.
> 
> need to double check it. I remember I tested it with the very first version of json generation in datafaker however I didn't do with the latest. Anyway comma also could be configurable
> 
> @mesketh let me know if you want to contribute a PR here (in this case i will remove this issue from my task list and will participate only in review)

Sure - although back at day job next week but, should be able to whip up something with a builder and some config parameters feeding into that for separator, etc.. Let me know any firmer thoughts than what's discussed herein ⬆️ .

**Comment by mesketh** [comment]
@snuyanzin et.al. I have a PR for this change. Can you add me as contributor/collaborator so i can push branch and raise PR. cheers.

**Comment by snuyanzin** [comment]
you don't need to have a collaborator's role to push PR.
Everyone can do it.

The process is the next one:
1. Fork this repo under your github account
2. push changes to your fork under a corresponding branch (not main)
3. Go to your fork via browser (may be refresh page) it will suggest you to create PR based on recently pushed changes

**Comment by mesketh** [comment]
Raised PR. @snuyanzin @bodiam

**Comment by snuyanzin** [comment]
merged as https://github.com/datafaker-net/datafaker/commit/9cb702b08a1de7c1eda4d6f644811b25df00bba0

**Comment by bodiam** [comment]
Hi all, thanks for this contribution, great work!
