### ISSUE TITLE
Computer brands feature request

### ISSUE THREAD

**Issue by HattoriHenzo** [datafaker-net/datafaker#652]
**Is your feature request related to a problem? Please describe.**
Very nice project by the way. I would like to update to Computer provider with computer brands. And after provide some more Providers.

**Describe the solution you'd like**
I would like to provide a code to update the Computer provider with available brands on the market such as: such as Apple, HP, Asus etc...

**Additional context**
We hope my contribution will help.

**Comment by bodiam** [comment]
Hi @HattoriHenzo , we would more than welcome such contribution! Feel free to make the changes, we can probably include this in the 1.8 release!

**Comment by kingthorin** [comment]
@HattoriHenzo are you tackling this?  If not I might take a shot at it.

**Comment by HattoriHenzo** [comment]
@kingthorin Hi, I already send a PR for this.

**Comment by kingthorin** [comment]
Oh sorry, I didn't see it linked here. I'll go find it.

**Comment by kingthorin** [comment]
I guess datafaker-net/datafaker#654 closes this :grinning:

For future reference :wink: https://docs.github.com/en/enterprise-server@3.4/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
