### ISSUE TITLE
Address deprecation

### ISSUE THREAD

**Issue by kingthorin** [datafaker-net/datafaker#666]
In order move toward implementing `Xlint` and ensuring we don't have any compiler warnings. A first somewhat easy step is to address deprecation.

We can limit to deprecation concerns `-Xlint:deprecation`, but the catch is that whenever we deprecate something we'd also have to stop using it internally. Which really should be true anyway IMHO but isn't necessarily quick or straight forward.

On that limited front here's what we'd have to address:
```console
[WARNING] /C:/datafaker/src/main/java/net/datafaker/service/FakeValuesService.java:[447,20] net.datafaker.formats.Csv in net.datafaker.formats has been deprecated
[WARNING] /C:/datafaker/src/main/java/net/datafaker/service/FakeValuesService.java:[447,43] net.datafaker.formats.Csv in net.datafaker.formats has been deprecated
[WARNING] /C:/datafaker/src/main/java/net/datafaker/service/FakeValuesService.java:[457,9] net.datafaker.formats.Csv in net.datafaker.formats has been deprecated
[WARNING] /C:/datafaker/src/main/java/net/datafaker/service/FakeValuesService.java:[457,36] net.datafaker.formats.Csv in net.datafaker.formats has been deprecated
[WARNING] /C:/datafaker/src/main/java/net/datafaker/service/FakeValuesService.java:[460,30] net.datafaker.formats.Csv in net.datafaker.formats has been deprecated
[WARNING] /C:/datafaker/src/main/java/net/datafaker/service/FakeValuesService.java:[462,16] net.datafaker.formats.Format in net.datafaker.formats has been deprecated
[WARNING] /C:/datafaker/src/main/java/net/datafaker/transformations/JavaObjectTransformer.java:[20,31] newInstance() in java.lang.Class has been deprecated

```

_Originally posted by @kingthorin in https://github.com/datafaker-net/datafaker/pull/663#discussion_r1096534504_

---

To get warnings from xlint we'd do this:

```diff
warning: in the working copy of 'pom.xml', CRLF will be replaced by LF the next time Git touches it
diff --git a/pom.xml b/pom.xml
index 0c0b607b..d8e4e945 100644
--- a/pom.xml
+++ b/pom.xml
@@ -176,6 +176,9 @@
                     <configuration>
                         <source>${maven.compiler.source}</source>
                         <target>${maven.compiler.target}</target>
+                        <compilerArgs>
+                            <arg>-Xlint:all</arg>
+                        </compilerArgs>
                     </configuration>
                 </plugin>
                 <plugin>
```

To have those warnings error (and fail builds) we'd add another arg entry `<arg>-Werror</arg>`.

There are quite a large number of warnings. Shall I open an issue adding the output? So that we can discuss further. I'm not sure the best way to tackle it. I definitely don't know enough about the code base yet to tackle it all.

---

https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html#BHCJCABJ

**Comment by bodiam** [comment]
Hi @kingthorin , sorry, I don't get this change, or the related changes. I'm trying to run `ProvidersDocsGenerator`, but I'm getting an `java: warnings found and -Werror specified` error when I run anything. Can you explain what this is, and how I can run the current code as is? Thanks.

**Comment by kingthorin** [comment]
To get around the issue you can comment `<!-- …. -->` the Werror line in pom.xml .

This is running in ci now so I don’t understand why you’re encountering it in a one-off situation, unless the code you’re using isn’t triggered during our ci or local maven executions (Ex: `.\mvnw install`)?

**Comment by bodiam** [comment]
Hi @kingthorin , thanks for the quick response. I've reverted the PR for now, since I can't run a single unit test nor generator from IntelliJ. If I clean the project, run a single test, the compilation fails. I don't think that's ideal, so I've reverted this change until I better understand what's causing this. `mvnw install` works fine, it's just running from my IDE which breaks.

**Comment by kingthorin** [comment]
Are you using `mvnw` to somehow run your one-off tests or some IntelliJ functionality?

**Comment by bodiam** [comment]
I don't think I'm using `mvnw`, nor would I use `mvnw` to run the `ProvidersDocsGenerator` or `ProviderGenerator`, which are failing for the same reason as running any test.

This is my configuration, I think it's pretty default:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/46468/218257120-018f71d4-d3f1-4372-89f1-0f9656866c64.png">

**Comment by kingthorin** [comment]
Okay, thanks I'll dig into it.

**Comment by bodiam** [comment]
Thanks! Btw, are you using Eclipse, since you don't seem to have this issue?

**Comment by kingthorin** [comment]
Yes I am using Eclipse. But I've been working with a combination of Eclipse and mvnw at the CLI to work around any weirdness I was encountering.

It's just a bumpy road getting in to a new project, maybe I moved on the Xlint stuff too quickly. I'll work on getting it all sorted out. I can also install IntelliJ on a VM and see how it behaves.

**Comment by kingthorin** [comment]
I futzed with this a bit more on the weekend. I think IDEs try to be helpful and apply the maven settings even when maven isn’t being used (Ex: the scripts and tests). 

I’m not sure if there’s a simple way around that, I’ll research/test further.

**Comment by bodiam** [comment]
I think with IntelliJ, if you have either maven or gradle, intellij will delegate the build to those tools instead of using its own builder. Would that affect this behavior?

**Comment by kingthorin** [comment]
Yes exactly, since these setting were being specified in the maven pom I believe IntelliJ and Eclipse apply the settings to all code in the project.

I’ll investigate if there’s a way to control that more finely with maven (or the IDEs).

**Comment by bodiam** [comment]
@kingthorin what do you want to do with this issue?

**Comment by kingthorin** [comment]
I’m still trying to see if there are good options for the Xlint stuff. Separate from that I’d have to look at whether or not we still have deprecated code in use.

**Comment by bodiam** [comment]
Yeah, I thought about cleaning up all the deprecated code too, but it doesn't matter, we will deprecate more code in the future as part of the releases, so we will run into the same problems again then.

**Comment by kingthorin** [comment]
If we’re deprecating code we shouldn’t be using it ourselves, that’s the thing.

The problem isn’t having things annotated deprecated, it’s that we have (or had) places internally still using those methods etc

**Comment by snuyanzin** [comment]
wouldn't it be better to split this task in several dedicated tasks (one per corresponding deprecated usage)?
Then for any new deprecated usage there could be another task created. It will allow to have much clear understanding what should be done to close this or that task. I'm suggesting this since right now current task seems never ending since there will be potentially other deprecations in future

**Comment by bodiam** [comment]
> If we’re deprecating code we shouldn’t be using it ourselves, that’s the thing.
> 
> The problem isn’t having things annotated deprecated, it’s that we have (or had) places internally still using those methods etc

Our current practice is that we never break the API without deprecating things. It isn't really semver, but we would be at Datafaker 25 by now if we did. 

There will always be some internal usage, even if it's by tests only, but we also deprecate things as a signal to show that in the near future we will replace it by something else, so I don't think we can ever avoid deprecating things, or banning the complete use of it.

**Comment by kingthorin** [comment]
Again the issue isn’t the existence of deprecated code it’s the use of it. If we deprecate something we should cease using it internally.

I’m obviously not getting my point across and don’t have time to dig into this right now so I’ll just close it.

**Comment by bodiam** [comment]
> Again the issue isn’t the existence of deprecated code it’s the use of it.

But I said:

> There will always be some internal usage, even if it's by tests only, 

Maybe I'm misunderstanding you or the feature, but if we'd deprecate a feature, that doesn't mean that immediate there can't be no usage of it, even if the usage is just a test for example (though I can image that someone might mark a piece of code deprecated to signal this code shouldn't be used anymore, but might still exist for a short while, while being used)

**Comment by kingthorin** [comment]
My argument is that if we deprecate something we "should" stop using it internally. That should be part of the PR that deprecates it :wink: The tests should be for the functionality that will be maintained.
