### ISSUE TITLE
1.8.0 release

### ISSUE THREAD

**Issue by bodiam** [datafaker-net/datafaker#670]
The general idea is to release a new version of Datafaker every 100 stars. It's a bit of an arbitrary metric, but seems to work okay for the time being.

Since we are almost at 500 stars, a new release is getting close. So, if you want to  include something in the 1.8.0 release, this is the moment!

**Comment by snuyanzin** [comment]
I would suggest to make the latest release with jdk8 support and then make jdk11 as the minimum.
The reason behind that is the fact that more and more libs including our dependencies started to require jdk11 as minimum e.g. spotless

WDYT?

**Comment by bodiam** [comment]
I'm not sure. I don't think spotless is a must have to for the library to be on Java 11, nor is Mockito 5.

Funny thing is that last time you convinced me to stick to Java 8, but at this moment I don't really see a great reason to require Java 11 as a minimum.

**Comment by snuyanzin** [comment]
well currently it looks like as a yellow flag that some dependencies started stopping support for jdk8.
We could live with that, let's see.

**Comment by bodiam** [comment]
I agree with you, and I expect that most people who use Datafaker are on a more modern stack than Java 8, but sticking on Java 8 might make a transition from Javafaker to Datafaker easier. 

I don't mind to much either way, happy to move to Java 11 or 17. I mean, Spring (Boot) did too.

**Comment by kingthorin** [comment]
I'm new around here so I don't want to sway things too much. 

For zaproxy we do have anonymous telemetry on JRE usage. We recently decided that the shift was sufficient to drop Java 8 support and make our minimum Java 11. 

I don't think there's a rush to move but with Java going to a 6mo cycle and more and more users trying to stay up-to-date a wide support range is going to become more and more difficult (I think).

**Comment by bodiam** [comment]
Thanks for the input @kingthorin . Do you think there's value of moving to Java 11 instead of 17? 

In my opinion, with Java 17 we can at least do something nice with records, but I don't really see the benefit for us of using Java 11. Thoughts?

**Comment by kingthorin** [comment]
I’d have to look at the numbers again. It partially depends what the majority of Linuxes are shipping with by default. Whatever you/we shift to it should be an LTS version (which I believe includes 17).

I’ll try to dig up some details.

**Comment by snuyanzin** [comment]
> sticking on Java 8 might make a transition from Javafaker to Datafaker easier.

well, there are multiple datafaker releases giving a way more features and a way more speed without any complexity for transition. So it should not be an issue to switch to e.g. 1.7.0 datafaker and then, if for whatever reason it's impossible with one jump, move to latest datafaker version.
so i think we can move to jdk17 as well.

**Comment by kingthorin** [comment]
Here's some stats for another project over the last month.

|row    |jv    |count|
|------|----|------|
|1    |11    |329202 |
|2    |17    |249099 |
|3    |19    |91345  |
|4    |1    |36543   |
|5    |15    |35849  |
|6    |18    |24180  |
|7    |13    |9857   |
|8    |16    |5405   |
|9    |14    |2364   |
|10    |18-ea    |108|
|11    |12    |861   |
|12    |10    |252   |
|13    |9    |213    |
|14    |20-ea    |84 |
|15    |19-ea    |62 |
|16    |13-ea    |19 |
|17    |17-ea    |12 |
|18    |16-ea    |10 |
|19    |17-internal| 9  |
|20    |21-ea    |4  |

As you can see Java 11 is still significantly more popular than 17. However, neither are a trivial number versus other options. (Note: There is no 8 as in our current version we've moved to min 11.)

**Comment by bodiam** [comment]
In that case, I'm happy to move to Java 17+, and call it Datafaker 2.x to make the distinction clear. Any objections to that? Happy to make 1.8 the last Java 8 release. Nice coincidence :-)

**Comment by kingthorin** [comment]
Sure that’s fine with me.

We will need to search the code base for since 1.8.0 annotations and update them. Along with updating the build config, etc.

**Comment by bodiam** [comment]
> We will need to search the code base for since 1.8.0 annotations and update them. Along with updating the build config, etc.

Not sure what you mean here. Why do I need to search, and what for?

**Comment by kingthorin** [comment]
`@since 1.8.0` ➡️ `@since 2.0.0` for stuff that’s been added after 1.7.0

**Comment by kingthorin** [comment]
Oh or maybe I’m misunderstanding your plan. Did you mean:

Next release 1.8.0 stick with Java 8.
Then 2.0.0 moving to min Java 17.

Or, did you mean just create a totally different package as datafaker2 (I hope not this).

**Comment by bodiam** [comment]
> Happy to make 1.8 the last Java 8 release.

I meant that the current release will still be on Java 8, so the since 1.8.0 will still be relevant. After the 1.8.0 release we switch to Java 17 and continue the work, but we'll work on 2.0.0-snapshot as the next release.

The 1.X version will no longer be maintained.

**Comment by kingthorin** [comment]
Alright, yup that plan seems good to me.

**Comment by bodiam** [comment]
We’ve reached 500 stars! ⭐ 

I’ll try to release 1.8 this weekend, so if anyone is keen to have any last minute changes, this is the moment!

**Comment by kingthorin** [comment]
It would be good to get this in for 1.8.0: https://github.com/datafaker-net/datafaker/pull/680 😀

**Comment by jpeffer** [comment]
@bodiam not sure if now is a good time, but we are revisiting the use of datafaker at my company and still would like to see setting and getting a random seed added to the library. This was originally requested in https://github.com/datafaker-net/datafaker/issues/188 and a subsequent PR was rejected for its breaking changes I believe. I do see some similar changes have been made since however. 

I know originally you were concerned that if we added a constructor that accepted a seed and a getter to retrieve the seed used, what would the getter return if a Random was passed in? While I still believe a constructor that accepts a Random is problematic, one simple work around could simply be to have the getSeed method throw an exception stating that the seed was not explicitly set and is unknown. That might allow you to not worry about the breaking change, while still supporting the use case we are hoping can be added.

**Comment by bodiam** [comment]
@jpeffer please open a new issue for this.

**Comment by bodiam** [comment]
1.8.0 has been released! 🥳
