### ISSUE TITLE
Token faker

### ISSUE THREAD

**Issue by RafaelBelo14** [datafaker-net/datafaker#673]
**Describe the solution you'd like** 
A token faker with base64 or other token formats.

**Comment by kingthorin** [comment]
What type of tokens are you thinking here?

**Comment by snuyanzin** [comment]
btw datafaker provides an ability to implement your own provider (more details with examples at https://www.datafaker.net/documentation/custom-providers/)
So you could implement such token support provider yourself and use with datafaker in your project and (in case there is a wish) submit a pr here

**Comment by RafaelBelo14** [comment]
The ability to fake server tokens. 

> btw datafaker provides an ability to implement your own provider (more details with examples at https://www.datafaker.net/documentation/custom-providers/) So you could implement such token support provider yourself and use with datafaker in your project and (in case there is a wish) submit a pr here

I will check it out, thank you!

**Comment by kingthorin** [comment]
Okay so we're talking JWT?

**Comment by bodiam** [comment]
> The ability to fake server tokens.
> 

What is a server token? Can you give an example, and explain how you would normally acquire one?

**Comment by RafaelBelo14** [comment]
> Okay so we're talking JWT?

Yes

**Comment by bodiam** [comment]
@RafaelBelo14 sounds like a good idea, happy to accept your PR  on this if you want to contribute, and happy to provide assistance if you have questions on this!

**Comment by RafaelBelo14** [comment]
I'm happy to contribute to the project! I will explore the custom providers, and submit a PR

**Comment by bodiam** [comment]
@RafaelBelo14 happy of you want to contribute, but for now I'll close this ticket.

**Comment by bodiam** [comment]
> Every user is going to have different and specific needs for the header, payload, and signature.

Maybe something like the transformers approach could help in building a valid JWT?
