### ISSUE TITLE
Any plans/schedule for 1.2.0 release?

### ISSUE THREAD

**Issue by tzolov** [datafaker-net/datafaker#69]

**Comment by snuyanzin** [comment]
as far as I know @bodiam is planning to have it in coming future https://github.com/datafaker-net/datafaker/issues/45#issuecomment-1047793444

@bodiam please correct me if I'm wrong

**Comment by bodiam** [comment]
Plan is this weekend, just writing some documentation

**Comment by bodiam** [comment]
Hi @tzolov , @snuyanzin , documentation has been published, and release is in Maven Central. Christian, if you could give it a shot, would love to hear your feedback. The release notes can be found here: https://www.datafaker.net/releases/1.2.0

**Comment by tzolov** [comment]
Hi @bodiam , my tests run fine with 1.2.0. Thanks!

**Comment by bodiam** [comment]
Great to hear, and thanks for testing @tzolov !
