### ISSUE TITLE
Data generation repeatability

### ISSUE THREAD

**Issue by jpeffer** [datafaker-net/datafaker#692]
**Is your feature request related to a problem? Please describe.**
In order to support data generation repeatability, it is important to be able to easily set and get the Random seed. When generating data for test automation runs, logging the seed allows for test repeatability in case of failures. Being able to get the seed, set the seed, and pass the configuration through to other internally called providers allows for greater flexibility. 

A similar need to get the Locale of a provider exists as well, though this may have been introduced in recent version. I believe the updated API may provide access now through the FakerContext, which is great. 

**Describe the solution you'd like**
Allowing a Random object to be a constructor parameter can also lead to unintentional consequences if that Random object is later altered by another thread. It also does not support retrieval of the seed. Changing the constructor to instead allow only a seed to be passed, allows the library to retain the seed used and expose it to through a getter, which can then be used to pass along that configuration when needed

Access to the RandomService and Locale through the FakerContext would support my need. The only missing piece then would be updates to the Faker constructor and RandomService. 

**Describe alternatives you've considered**
Alternatively, an additional constructor could be introduced to set the seed, expose it through a getter, and throw an exception from the getter if the seed was never set. This would allow for the current API to not break existing usages. The existing Faker constructor accepting a Random could be deprecated and removed in a 2.x release if desired. 

**Additional context**
Ultimately, I am trying to support the creation of a fluent API that allows for generation of valid and invalid test data for positive and negative test cases. The objects being created are complex where many of the data providers need to call other data providers. Some providers may even want to generate data in multiple locales. For example, a Client provider generator address data for that client where it has postal addresses in multiple countries or contacts of people with names from different countries. If a test failure occurs, there is a need to regenerate that exact data to evaluate the system under those conditions, which requires the ability to set the seed to what was originally used during the initial test run. 

This request was originally opened under https://github.com/datafaker-net/datafaker/issues/188

A PR was originally put forward to address this request, but has since become outdated. The foundation however is still relevant and can be seen here:

https://github.com/jpeffer/datafaker/blob/feature/core-api-refactor/src/main/java/net/datafaker/core/BaseFaker.java
https://github.com/jpeffer/datafaker/blob/feature/core-api-refactor/src/main/java/net/datafaker/service/RandomService.java

**Comment by snuyanzin** [comment]
May be I didn't get your case... Am I right that you want to set seed and get same seed (the value that was set and NOT the current seed value after several next invocations...) ? At least that is what i see in the code you've mentioned.
For this goal it possible to use `doWith` functionality where seed could be specified.

>The existing Faker constructor accepting a Random could be deprecated and removed in a 2.x release if desired.

what is the rationale behind that? Lots of users do not care about current seed and they will be impacted. (simple case production like data generation)

**Comment by jpeffer** [comment]
I think it's important to be able to log the seed that was used during data generation. Since Random has no safe or official way of getting the seed that was used, you need to explicitly set the seed to know what was used. That's integral to being able to replicate data generation for the system under those exact test conditions. 

The other important thing is that I want to be able to use providers from within another provider and they need access to the same configuration. 

I believe it makes sense to allow the library to abstract this from the consumer. Passing the Random object and allowing it to modify the behavior of data generation by reference, is not an API best practice. 

> Lots of users do not care about current seed and they will be impacted. (simple case production like data generation)

Yes, dropping support for passing in Random in favor some the seed is a breaking change, but ultimately it would not remove functionality. So I'm not really following your production like data generation example. Can you phrase the concern in another way? Maybe you could detail the current use case for that constructor and give an example of how its used today in comparison to my proposal.

**Comment by kingthorin** [comment]
This seems like a lot of data to just get static values in the end. Why not just generate your values once and hardcode or otherwise statically provide them?

**Comment by jpeffer** [comment]
I guess I'm being far from clear. The goal is to generate data dynamically as it does today, but other data generation frameworks support repeatability through setting the seed to regenerate the data if and when the need arises. So the normal use case is randomly generated data. On occasion, you may want to regenerate the same set of data to either determine root cause or prove resolution.

**Comment by bodiam** [comment]
I don't see why you don't wrap Datafaker with a wrapper class, keep the seed there with a Datafaker insurance, and have full control over the seed there when you need it.

**Comment by jpeffer** [comment]
Can I create a wrapper? Sure. Should consumers of the library need to? I don't believe so. I see this as a core feature that data generation libraries should provide as it is common need and is a feature found in most data generator solutions. A search on repeatable data generators uncovers it as a common and important theme. 

https://www.google.com/search?client=firefox-b-1-d&q=repeatable+data+generators

I get the hesitancy to break the existing API, but the 2.x release would seemingly provide the opportunity to make a clean break to support this through a mechanism that makes sense to me at least. Is there another use case I might be overlooking that the current interface helps to support over what I proposed? 

The change feels relatively small and adoption for existing consumers can be supported through a search and replace all, so it's not extremely intrusive. I'm also happy to contribute.

**Comment by snuyanzin** [comment]
I still don't get what seed are going to log, I mean this question
>Am I right that you want to set seed and get same seed (the value that was set and NOT the current seed value after several next invocations...) ?

in case it is only about the value that was set then why couldn't it be logged beforehand?

>I think it's important to be able to log the seed that was used during data generation. Since Random has no safe or official way of getting the seed that was used, you need to explicitly set the seed to know what was used. That's integral to being able to replicate data generation for the system under those exact test conditions.

in fact users never know. during generation datafaker could use several values. E.g. there is a list of macroses in `yaml`. The first it needs to pick a random macros, then it should generate a value based on macros, may be something else because sometimes macros could consist of several expressions e.g. And sometimes there could be some optimizations done on datafaker's code leading to reducing of random usage. As a result next release logged numbers could be different. 

Or may be you have more code examples explaining what you expect?  I was able to see only getter to get the initial seed https://github.com/jpeffer/datafaker/blob/92d6c12bb5ce06a1dc34f97efc39c7e8182f7568/src/main/java/net/datafaker/service/RandomService.java#L104-L106
Initial value could be logged beforehand, or anyway you have info about outside of `Random` just because initial value came outside, right?

>Yes, dropping support for passing in Random in favor some the seed is a breaking change, but ultimately it would not remove functionality.

first i'd love to understand what to sacrifice for.

> Can you phrase the concern in another way? Maybe you could detail the current use case for that constructor and give an example of how its used today in comparison to my proposal.

here it is an example with code how some people use it https://github.com/DiUS/java-faker/issues/663

>I get the hesitancy to break the existing API, but the 2.x release would seemingly provide the opportunity to make a clean break to support this through a mechanism that makes sense to me at least. Is there another use case I might be overlooking that the current interface helps to support over what I proposed?

can you give a piece of code clearly showing what would be possible after that change that is impossible right now? I'm asking because currently I don't understand it

**Comment by bodiam** [comment]
> Can I create a wrapper? Sure. Should consumers of the library need to? I don't believe so. I see this as a core feature that data generation libraries should provide as it is common need and is a feature found in most data generator solutions. A search on repeatable data generators uncovers it as a common and important theme.
> 
> https://www.google.com/search?client=firefox-b-1-d&q=repeatable+data+generators

It looks like you're saying two things here. Repeatable data is important, and I agree on that, and that's why we have put a lot of effort in making sure this happens. Have a look at `FakerRepeatabilityIntegrationTest` as an example, that test guarantees that all fakers generate the same data given a certain seed, so providing a seed isn't an issue here.

Retrieving the seed is a whole different issue, and quite a specific one. In the lifetime of Javafaker and Datafaker, which is now over 9 years, there has been no attempt to request such a feature, so I doubt that this is as important for most people as it is for you. Hence, yes, create a wrapper for it. It's a class of only a few lines:

```
class Wrapper(seed: Int) {
    val faker: Faker
    val seed: Long

    init {
        faker = Faker(Random(seed.toLong()))
        this.seed = seed.toLong()
    }
}
```

or Java:

```
public class Wrapper {

    private final Faker faker;
    private final long seed;

    public Wrapper(int seed) {
        this.faker = new Faker(new Random(seed));
        this.seed = seed;
    }

    public long getSeed() {
        return seed;
    }

    public Faker getFaker() {
        return faker;
    }
}
```

So, no, I don't see a reason why you can't use a wrapper in your code, or why we should break the API for your usecase, and it's still quite unclear to me why we should do that.

**Comment by jpeffer** [comment]
Perhaps no one has requested it and I still do agree I can get around this, but I still see this as a core enhancement to the current functionality in comparison to some other libraries. You also don't have to decide to break the API for this use case. It can be added without breaking anything, but would result in a getter that either simply returned null or threw an error if it didn't know the seed. 

I guess I have a few remaining questions:

- Between test runs, how can your library support test reproducibility?
- Is that simply through the wrapper approach? 
- Is that really a unique need from your perspective?

I really was hoping to contribute and I am not trying to be argumentative, but I am surprised at this not being seen as a valuable addition. I'll drop the request if you still feel there is no value and I appreciate the discussion.

**Comment by snuyanzin** [comment]
>Between test runs, how can your library support test reproducibility?

seems we still do not understand each other.
Let's switch to the code
here it is an example of repeatable generation
```java
    @Test
    void shouldCreateRepeatableValues() throws InvocationTargetException, IllegalAccessException {

        Faker faker1 = new Faker(new Random(0));
        Faker faker2 = new Faker(new Random(0));

        Map<String, String> report1 = buildReport(faker1);
        Map<String, String> report2 = buildReport(faker2);

        assertThat(report1).isEqualTo(report2);
    }
```

Could you please tell us what is the problem here and how this problem could be solved with your solution?

**Comment by bodiam** [comment]
It seems this conversation is going in the same direction as last time, which doesn't feel productive, plus you seem to selectively ignore our feedback.

As we explained several times now, we do support test reproducibility, simply by supplying a Random with a seed when creating a Faker instance. If you want to keep track of the seed, do so, but it's  not the responsibility of Datafaker to provide this seed, especially not with such a simple workaround. 

You have not provided any feedback on why such a wrapper class would be unsuitable, so it would be hard to help you without providing a full picture.

**Comment by jpeffer** [comment]
I'm not trying to selectively ignore your feedback, so I'm sorry you feel that way. I am apparently doing a poor job communicating why I feel the suggested change would be beneficial to the library. 

Ultimately, the wrapper you suggest meets my needs, but I don't believe it should be a responsibility of the consumer as it pushes the responsibility of managing the seed used outside of the library.

```java
Random random = new Random();

Faker faker = new Faker(random);
random.setSeed(0);
```

Allowing for this can lead to unexpected behavior from a consumer, rather than just setting the seed itself. 

Also, it appears I entirely missed [snuyanzin](https://github.com/snuyanzin) comment from 12 hours ago, when reviewing from my phone, so I will review that as well. Apologies.

**Comment by bodiam** [comment]
> Allowing for this can lead to unexpected behavior from a consumer, rather than just setting the seed itself.

So does driving without a seatbelt, but while possible, it's not something you need to do. I've given you a code example, straight from our documentation by passing in a Random with a seed in the constructor. That this Random is mutable, that's unfortunate, but that can be limited by not keeping a reference to the Random object, and is beyond the scope of Datafaker.

I think at this moment we just have to conclude that Datafaker might not be the library for you, sorry for that.

**Comment by snuyanzin** [comment]
> Allowing for this can lead to unexpected behavior from a consumer, rather than just setting the seed itself.

then java is a dangerous language... it does not matter either it is done via wrapper or in datafaker the `setSeed` could be invoked again via reflection... 
at some point need to accept trade off and move forward

**Comment by kingthorin** [comment]
@jpeffer I don't think anyone was intending to be hostile. I think people were just getting frustrated feeling that they were going in circles. There had been a few requests for actual code examples, which never materialized. 

I think given that a seed can be provided and easily kept track of on the caller/consumer side with a few lines of code and already supported by datafaker functionality it seems like a no brainer. If we'd been suggesting a solution that required dozens or 100s of lines of code that would be a different story.

If you still feel that changes are warranted then providing an example (even "pseudo code") would probably go a long way to helping the conversation.
