### ISSUE TITLE
Unable to create custom provider using yaml file when bundled as a jar.

### ISSUE THREAD

**Issue by jwanggg** [datafaker-net/datafaker#714]
Following the instructions [here](https://www.datafaker.net/documentation/custom-providers/#custom-provider-using-yaml-file), I am able to create a custom provider that reads the yaml file from the file path. 

However when I bundle my app together and try to run it the same it can't find the path/uri correctly to create the custom faker.

I am using 
```
faker.addPath(Paths.get(this.getClass().getResource("testFaker.yml").toURI))
```
to get the yml file locally and create the custom provider.

When bundled as a jar the above fails due to path being invalid from a jar. The path ends up being something like ```jar:file:/mnt/kubernetes/sandbox/dist/lib/main.jar!/testFaker.yml```

I am forced to do something like 

```
            final InputStream is = getClass().getResourceAsStream(testFaker.json);
            return mapper.readValue(is, new TypeReference<Map<String, List<String>>>() {});
```

and making somewhat of a hardcoded custom provider.

Is it possible to add a faker path through the resource stream or any way to add support for it?

**Comment by kingthorin** [comment]
Is testfaker.yml really expected to be in the root of your jar?

**Comment by jwanggg** [comment]
> Is testfaker.yml really expected to be in the root of your jar?

I've put the testfaker.yml under the resources folder. The whole path would be /src/main/resources

**Comment by bodiam** [comment]
Try to load the file with a / in front of it, or move the file to the same directory as the source file is in.

**Comment by bodiam** [comment]
I think if you have the file under the root folder, you need to add an extra `/`, like this: 
```
faker.addPath(Paths.get(this.getClass().getResource("/testFaker.yml").toURI))
```

Otherwise, you might have to put the YML file in the same location as where the source file is.

**Comment by snuyanzin** [comment]
@jwanggg in case the issue still exists may I ask you to share the code to reproduce?
I can potentially have a look during the weekend

**Comment by jwanggg** [comment]
@bodiam the above works when I am running my code locally. The reason I had to use ```ResourceAsStream`` is because  in deployed environments, it loads out of a jar, not off the filesystem directly. When the resource is loaded out of a Jar, it isn’t a “normal” URL so the Path.get fails in the above example

**Comment by bodiam** [comment]
@jwanggg ahh, sorry, I see, it's doing the addPaths, that's not ideal indeed. We should maybe add an "addSource(InputStream)" method or so, would that be better?

**Comment by jwanggg** [comment]
> Absolutely. We should maybe add an "addSource(InputStream)" method or so, would that be better?

Yes that would be helpful!

**Comment by snuyanzin** [comment]
well after checking i can say that in fact there is support for other jar if a config as mentioned as a file via add path (not as a resource).
I would consider support for add as a resource as a separate new feature and it should be checked that new feature does not break the existing functionality

**Comment by bodiam** [comment]
> well after checking i can say that in fact there is support for other jar if a config as mentioned as a file via add path (not as a resource)

Sorry, I don't know what you're saying here. Do you mean that using the Path approach already works in a JAR?

**Comment by snuyanzin** [comment]
it works if a *.yaml is not a part of a jar, means that it should be a separate file

**Comment by bodiam** [comment]
But that's the point right? You want to bundle the YAML with the jar?

**Comment by snuyanzin** [comment]
Initially it was considered as not bundled.
Bundling makes sense however it should keep the functionality without bundling

**Comment by snuyanzin** [comment]
I reiterate the issue once again
1. @jwanggg you wrote 
 > Following the instructions [here](https://www.datafaker.net/documentation/custom-providers/#custom-provider-using-yaml-file), I am able to create a custom provider that reads the yaml file from the file path.

however there is nothing about add files as resources in description... So I guess you did not follow the instructions precise. In that case I would ask you to provide exact steps to reproduce the issue.

2. I created a separate app with custom faker retrieving files as resources and it works (the code snippet is below).
So i have no idea how to reproduce your issue. In case you are still interested in it please provide a minimum reproducing example.

```java
public class Issue714 {
    public static void main(String[] args) {
        System.out.println(BaseFaker.getProvider(InsectFromResources.class, InsectFromResources::new, new Faker()).bee());
    }

    public static class InsectFromResources extends AbstractProvider<BaseProviders> {
        private static final String KEY = "insectsfromfile";

        public InsectFromResources(BaseProviders faker) {
            super(faker);
            faker.addPath(Locale.ENGLISH, Paths.get(this.getClass().getClassLoader().getResource("ants-resources.yaml").getPath()).toAbsolutePath());
            faker.addPath(Locale.ENGLISH, Paths.get(this.getClass().getClassLoader().getResource("bees-resources.yaml").getPath()).toAbsolutePath());
        }

        public String ant() {
            return resolve(KEY + ".ants");
        }

        public String bee() {
            return resolve(KEY + ".bees");
        }
    }
}
```

**Comment by jwanggg** [comment]
@snuyanzin 
The code from the instructions works locally. It is only when the application is deployed to Kubernetes the file paths do not work as intended resource or file path. 
If anything something with this be exposed https://github.com/datafaker-net/datafaker/blob/53e14a4629bbca69707b48007644956d6dd80149/src/main/java/net/datafaker/service/FakeValues.java#L199. Like @bodiam mentioned above with addSource with the inputStream

**Comment by snuyanzin** [comment]
In a comment above i posted a comment with a code snippet working for the case when datafaker is an external lib.
Doesn't it solve the issue?
