### ISSUE TITLE
Refactoring: Using Implementation and Design/Architectural level refactoring to make the code better - without changing the behaviour.

### ISSUE THREAD

**Issue by almasfiza** [datafaker-net/datafaker#738]
**Refactoring**
Performing implementation and design/architectural level refactoring to make the code better, increase the readability and understandability of the code.

**Additional context**
Refactoring does not fit the category of either a feature or bug fix. Since there is no other category available, I am entering this issue as a Bug fix.

**Comment by kingthorin** [comment]
Please be much more specific.
1. Are you undertaking this activity? (Should it be assigned to you)
2. What is it you have trouble reading/understanding?
3. Do you intend to do this without breaking binary compatibility?

**Comment by snuyanzin** [comment]
can you please describe an issue with some code snippets to allow others understand what is problem?

**Comment by almasfiza** [comment]
1. Yes I am undertaking this activity.
2. I am trying to understand the code and look at options to refactor it. 
3. I am only focusing on changing the code structure without affecting the behavior. 

(I have an assignment for a graduate course on refactoring - and also this assignment aims to promote open source contribution.)

**Comment by almasfiza** [comment]
> can you please describe an issue with some code snippets to allow others understand what is problem?

![image](https://user-images.githubusercontent.com/62244354/228335203-7a904577-0fb5-427d-a17f-2f8869ffd976.png)
I just applied an extract method refactoring on one of the files - datafaker/src/main/java/net/datafaker/providers/base/Barcode.java

This makes it easier as it breaks the ean() function down.

**Comment by snuyanzin** [comment]
ok, I see.
Well, this is now java 17 and we could use its features.
All these lines to calculate `var` could be replaced with 3 lines `switch`
At the beginning of this method (`net.datafaker.providers.base.Barcode#ean`) you can see an example for `firstPart`.
In similar way it could be done here

Also i would rename `var` variable since now there is a similar keyword in java

**Comment by almasfiza** [comment]
> ok, I see. Well, this is now java 17 and we could use its features. All these lines to calculate `var` could be replaced with 3 lines `switch` At the beginning of this method (`net.datafaker.providers.base.Barcode#ean`) you can see an example for `firstPart`. In similar way it could be done here
> 
> Also i would rename `var` variable since now there is a similar keyword in java

![image](https://user-images.githubusercontent.com/62244354/228344124-b661c2a1-fd6c-422f-a3fb-4c7251c8c0b7.png)

**Comment by almasfiza** [comment]
> ok, I see. Well, this is now java 17 and we could use its features. All these lines to calculate `var` could be replaced with 3 lines `switch` At the beginning of this method (`net.datafaker.providers.base.Barcode#ean`) you can see an example for `firstPart`. In similar way it could be done here
> 
> Also i would rename `var` variable since now there is a similar keyword in java
![image](https://user-images.githubusercontent.com/62244354/228345247-66aea08b-80c6-43bf-abd8-b9a3322f25dd.png)

**Comment by snuyanzin** [comment]
currently your `switch` is NOT jdk13+ enhanced `switch`. The idea is to use enhanced `switch`.

**Comment by kingthorin** [comment]
I'm not against any of this. Obviously it's hard to provide feedback on just one simple example. But be careful with basics. Like this could just return the value instead of storing and breaking, then returning (or per the earlier screenshot, initializing an int to zero). Also the comment (`// Implementation...`) is handy here for discussion/clarity but isn't needed whenever this is PRd.

**Comment by almasfiza** [comment]
> I'm not against any of this. Obviously it's hard to provide feedback on just one simple example. But be careful with basics. Like this could just return the value instead of storing and breaking, then returning (or per the earlier screenshot, initializing an int to zero). Also the comment (`// Implementation...`) is handy here for discussion/clarity but isn't needed whenever this is PRd.

Okay, noted! Will work on it.

**Comment by almasfiza** [comment]
> currently your `switch` is NOT jdk13+ enhanced `switch`. The idea is to use enhanced `switch`.

Okay, I will look into it!

**Comment by snuyanzin** [comment]
by the way in github it's easy to create a PR or a draft PR and  people could comment on it. 
The code will be connected to the repo and it is much more convenient then each time trying to compare screenshot/whatever image with code

**Comment by almasfiza** [comment]
> by the way in github it's easy to create a PR or a draft PR and people could comment on it. The code will be connected to the repo and it is much more convenient then each time trying to compare screenshot/whatever image with code

Oh okay, thank you for your help! :)
