### ISSUE TITLE
Data provider `Oscar Movie` doesn't generate new values on each iteration

### ISSUE THREAD

**Issue by MartijnVisser** [datafaker-net/datafaker#741]
**Describe the bug**
When using the data provider `Oscar Movie`, all generated values are the same as previous results. 

**To Reproduce**
See https://github.com/MartijnVisser/datafaker-oscarmovie/blob/main/src/Main.java. Every run will generate the same 3 lines, for example:

```
Zero Dark Thirty
Zero Dark Thirty
Zero Dark Thirty
```

```
Sound of Metal
Sound of Metal
Sound of Metal
```

**Expected behavior**
A new value should be generate during each iteration, e.g.:
```
Zero Dark Thirty
Room
Sound of Metal
```

**Versions:**
 - OS: Macbook Pro Ventura 13.2.1 (22D68)
 - JDK: Temurin 17.0.5-tem
 - Faker Version [e.g. 22]. Tried both 1.8.1 and 2.0.0-SNAPSHOT

**Additional context**

**Comment by snuyanzin** [comment]
Thanks for the use case @MartijnVisser =)

It seems there is such issue of every method in `Oscar Movie`, not sure how we have not noticed that so far...

There is a PR fixing that behavior #742 , please double check whether it does the trick with your env.

**Comment by MartijnVisser** [comment]
> There is a PR fixing that behavior #742 , please double check whether it does the trick with your env.

Verified that it works. Thanks for the quick fix :)

**Comment by knaufk** [comment]
@snuyanzin Do you have an idea on when this bug fix will be released? I'd love to upgrade flink-faker to a version that includes this fix.

**Comment by knaufk** [comment]
In my understanding in order to use it widely with Apache Flink I'll need a Java 8/11 version unfortunately.

**Comment by snuyanzin** [comment]
ok, I see, we could backport it to 1.8.x branch.

about release @bodiam are ok to make one more 1.8.x?

**Comment by bodiam** [comment]
@snuyanzin yeah, absolutely, it takes less than 5 minutes, no problem!

**Comment by snuyanzin** [comment]
merged to 1.x as https://github.com/datafaker-net/datafaker/commit/dd3d99244936194cb421d1a1cb9eb58591e03fef

**Comment by snuyanzin** [comment]
@knaufk datafaker 1.9.0 containing this fix is now released
thanks to @bodiam

**Comment by knaufk** [comment]
Thanks a lot @bodiam and @snuyanzin!
