### ISSUE TITLE
Version 1.8.1 shaded the wrong version of snakeyaml

### ISSUE THREAD

**Issue by maokejackson** [datafaker-net/datafaker#764]
When refer to `datafaker-1.8.1.jar/META-INF/maven/org.yaml/snakeyaml/pom.xml`, the version is still 1.33 as shown below:

```
<groupId>org.yaml</groupId>
<artifactId>snakeyaml</artifactId>
<version>1.33</version>
<packaging>bundle</packaging>
```

**Comment by snuyanzin** [comment]
why do you think it is wrong if `pom.xml` from 1.8.x branch still depends on 1.33 ?
https://github.com/datafaker-net/datafaker/blob/7303fb2af6009260eea24116b0f570dfa98efebd/pom.xml#L50

**Comment by bodiam** [comment]
No libraries are shaded. If you want to upgrade the library, you can choose to use Datafaker 2 (snapshot) or include a newer version of snakeyml yourself.

**Comment by bodiam** [comment]
Oops, sorry, didn't know that! Either way, it's best if you can upgrade to Datafaker 2. The CVE isn't that bad anyway, it's  mainly dangerous when you allow data from untrusted sources.

**Comment by snuyanzin** [comment]
fixed within https://github.com/datafaker-net/datafaker/pull/771
