### ISSUE TITLE
Using with ColdFusion and/or Lucee CFML

### ISSUE THREAD

**Issue by JamoCA** [datafaker-net/datafaker#790]
## Describe the bug

I'd like to use this library with ColdFusion 2016-2021 and/or Lucee CFML. These web platforms run on Java.  I currently use a lot of third-party JARs in my existing ColdFusion projects.

I'm unable to reproduce the results of the simple example to generate a random full name.

## To Reproduce

Based on the [Getting Started | Usage](https://www.datafaker.net/documentation/getting-started/#usage) documentation, I thought it looked easy (based on past experience), but the following doesn't work.

```java
faker = createobject("java", "net.datafaker.Faker");
writedump(var=faker, label="faker object");
writedump(var=faker.name().fullName(), label="fullName");
```

If I dump `faker`, many methods are listed (addPath, addUrl, bothify, collection, csv, doWith, etc), but `name` isn't listed.

Instead of dumping a full name, a "The name method was not found." error message is returned.

## Expected behavior

I was expecting the example to work, but I'm guessing that extra configuration is required in order for it to work with ColdFusion.  Is DataFaker a standalone JAR or does it have additional dependencies?

## Versions:

 - OS: Windows 2016 Server
 - JDK: 19 (I don't think downgrading to 18 or 17 will make much difference. I've tried in the past too.)
 - Faker Version: 1.9.0
 - ColdFusion 2016,0,17,325979

## Additional context

This may be difficult to troubleshoot without a ColdFusion/CFML environment.  [CommandBox](https://www.ortussolutions.com/products/commandbox) is a free CLI that can "spin up an ad hoc, lightweight, ColdFusion (CFML) server (Lucee or Adobe ColdFusion) in any directory from the command line".  JAR files can be added to any project by adding some [extra configuration](https://www.ortussolutions.com/blog/how-can-i-use-a-jar-library-in-cfml) to the web root's `application.cfc` file. (I may be able to provide some initial framework to assist in this if anyone is interested.)

**Comment by bodiam** [comment]
Hi @JamoCA , interesting issue. How did you add the DataFaker library to your project? DataFaker isn't a library on its own, as in, we don't provide a fatjar containing all the dependencies, and while we try to keep the dependencies to a minimum, you need the following libraries (and its transitive dependencies, if any, though I don't think there are any) too:

* snakeyaml
* generex

You can find the exact dependencies here: https://github.com/datafaker-net/datafaker/blob/main/pom.xml#L75

Could you also post the output of the `writedump` command here, maybe that gives us some insight.

**Comment by JamoCA** [comment]
Some projects offer a precompiled JAR for download and list all dependencies.  I wasn't sure what I needed and downloaded `datafaker-1.9.0.jar` from this website:
https://mvnrepository.com/artifact/net.datafaker/datafaker/1.9.0
_(This JAR resource site is linked to from this project's [README](https://github.com/datafaker-net/datafaker/blob/main/README.md) file.)_

I see that if I download it from here:
https://jar-download.com/?search_box=datafaker
that these JARs dependencies are automatically included in a zip file and the datefaker JAR is the same as mvnrepository:
- automaton-1.11-8.jar
- datafaker-1.9.0.jar
- generex-1.0.2.jar
- snakeyaml-2.0.jar

I've added all of these files to path file that ColdFusion uses to load all JAR files and there wasn't any difference.

Here's a screenshot of the dump of net.datafaker.Faker`.
![datafaker-dump-20230427190245](https://user-images.githubusercontent.com/1112671/235037679-0514a1f3-feda-45b7-88e1-7034e8ea15e2.png)

**Comment by bodiam** [comment]
> Some projects offer a precompiled JAR for download and list all dependencies.

We expect people to use a package manager like Maven or Gradle. You shouldn't download it from the Maven Repository directly unless you know what you're doing, but in general, that's not a recommended approach.

Thanks. I don't know why that dump doesn't show the methods of the interfaces, but `Faker` implements a couple of interfaces, one of them being `BaseProviders`, which provides the `name()` method.

What happens when you do something like `invoke(createObject("java", "net.datafaker.Faker"), "name")`? Does that result in an error message? If so, which?

**Comment by JamoCA** [comment]
Macomedia rewrote ColdFusion top run on Java back in 2002 and I haven't had to use Maven or Gradle package managers in order to leverage java in any of my applications.  I've used ~50 different java libraries for things like chart generation, hashIds, mongoDB, iText, zxing, jUnidecode, emoji-java, oneLogin SAML, opencsv, mssql-jdbc, jsoup, pdfbox and dropboxContentHasher and none of them have required the use of a package manager.

I noticed one thing... when I dump other java objects, they have direct methods.  The `net.datafaker.Faker` object doesn't have any direct methods.  It contains a "Parent Class" which has methods, but the initial object has no methods of its own.

I found a [workaround](https://stackoverflow.com/a/17285134/693068) regarding a possible reflection bug mentioned on StackOverflow and I was able to get something to work using CF2016, but it's not pretty.

```java
faker = createobject("java", "net.datafaker.Faker");
cfsilent() {
	// CFBug? if writedump is omitted, an error occurs when performing invoke. #SMH
	writedump(var=faker, label="faker", format="text");
};
nameClass = faker.getClass().getMethod(javacast("string", "name"), []);
name = nameClass.invoke(faker, []);

startTime = gettickcount();
writeoutput("<div><b>firstName:</b> #name.firstName()#</div>");
writeoutput("<div><b>fullname:</b> #name.fullname()#</div>");
writeoutput("<div><b>lastname:</b> #name.lastname()#</div>");
writeoutput("<div><b>name:</b> #name.name()#</div>");
writeoutput("<div><b>nameWithMiddle:</b> #name.nameWithMiddle()#</div>");
writeoutput("<div><b>prefix:</b> #name.prefix()#</div>");
writeoutput("<div><b>suffix:</b> #name.suffix()#</div>");
writeoutput("<div><b>title:</b> #name.title()#</div>");
writeoutput("<div><b>username:</b> #name.username()#</div>");
writeoutput("<div><b>Duration:</b> #numberformat(gettickcount() - startTime)# ms</div>");
writedump(var=name);
```
This above CFML will generate the following output.
![image](https://user-images.githubusercontent.com/1112671/235066219-d2a63a9c-c8a4-4083-8b3d-3afbab2efb08.png)

**Comment by JamoCA** [comment]
Macomedia rewrote ColdFusion top run on Java back in 2002 and I haven't had to use Maven or Gradle package managers in order to leverage java in any of my applications.  I've used ~50 different java libraries for things like chart generation, hashIds, mongoDB, iText, zxing, jUnidecode, emoji-java, oneLogin SAML, opencsv, mssql-jdbc, jsoup, pdfbox and dropboxContentHasher and none of them have required the use of a package manager.

I noticed one thing... when I dump other java objects, they have direct methods.  The `net.datafaker.Faker` object doesn't have any direct methods.  It contains a "Parent Class" which has methods, but the initial object has no methods of its own.

I found a [workaround](https://stackoverflow.com/a/17285134/693068) regarding a possible reflection bug mentioned on StackOverflow post from 2013.  I was able to get something to work, but it's not pretty.

```java
faker = createobject("java", "net.datafaker.Faker");
cfsilent() {
	// CFBug? if writedump is omitted, an error occurs when performing invoke. #SMH
	writedump(var=faker, label="faker", format="text");
};
nameClass = faker.getClass().getMethod(javacast("string", "name"), []);
name = nameClass.invoke(faker, []);

startTime = gettickcount();
writeoutput("<div><b>firstName:</b> #name.firstName()#</div>");
writeoutput("<div><b>fullname:</b> #name.fullname()#</div>");
writeoutput("<div><b>lastname:</b> #name.lastname()#</div>");
writeoutput("<div><b>name:</b> #name.name()#</div>");
writeoutput("<div><b>nameWithMiddle:</b> #name.nameWithMiddle()#</div>");
writeoutput("<div><b>prefix:</b> #name.prefix()#</div>");
writeoutput("<div><b>suffix:</b> #name.suffix()#</div>");
writeoutput("<div><b>title:</b> #name.title()#</div>");
writeoutput("<div><b>username:</b> #name.username()#</div>");
writeoutput("<div><b>Duration:</b> #numberformat(gettickcount() - startTime)# ms</div>");
writedump(var=name);
```
This above CFML will generate the following output.
![image](https://user-images.githubusercontent.com/1112671/235066219-d2a63a9c-c8a4-4083-8b3d-3afbab2efb08.png)

**Comment by kingthorin** [comment]
Still looking for:

> What happens when you do something like `invoke(createObject("java", "net.datafaker.Faker"), "name")`? Does that result in an error message? If so, which?

**Comment by JamoCA** [comment]
I guess I would have commented on this if it were slightly successful, but the error message is exactly as the initial issue that I reported... `The name method was not found.`

Here's a screenshot.

![image](https://user-images.githubusercontent.com/1112671/235168413-d8609b3d-85d2-44ad-8bf9-cd19c500b446.png)

**Comment by kingthorin** [comment]
Thanks

**Comment by bodiam** [comment]
What  happens when you create your own classes, something like:

interface SuperInterface {
 default String method1() { return "1";} 
}

class Subclass implements Super nterface {
 String method2() { return "2"}
}
 

If you do this, what happens when you invoke method1 and method2 using CFML?

**Comment by JamoCA** [comment]
Not sure... I usually develop primarily/solely in CFML (which is JIT-compiled at runtime) and leverage existing third-party JARs, so I don't have much experience with creating native java interfaces.

I just tested using ColdFusion 2021 and the results of the object dump of `net.datafaker.Faker` was consistent with the first screenshot that I shared (none of the provider methods are directly accessible), but unlike CF2016 it doesn't throw an error.  The `name` method is not listed, but dumping `faker.name()` displays a list of familiar methods.  (I haven't tested CF2018 & CF2016 recently reached EOL.)

```java
// using ColdFusion 2021 (this doesn't work in CF2016)
faker = createobject("java", "net.datafaker.Faker");
writeoutput(faker.name().fullName());
writedump(faker.name());
```
![datafaker-cf2021-20230429123135](https://user-images.githubusercontent.com/1112671/235320976-e90bb5e9-fbe9-4f74-9813-4c0fe2f455d9.png)

**Comment by kingthorin** [comment]
So you’re good now?

**Comment by snuyanzin** [comment]
It looks like your tool (CFML) is unable to dump method declared as **default interface methods**. 'name()` and others you could find at https://github.com/datafaker-net/datafaker/blob/main/src/main/java/net/datafaker/providers/base/BaseProviders.java

Thus this issue should be addressed to maintainers of CFML

**Comment by JamoCA** [comment]
@kingthorin Yes. An outdated version of DataFaker is required to work with the outdated version of ColdFusion due to interface implementation.

@snuyanzin version 2016 of ColdFusion (which is EOL as of 2/17/2022) is incapable of accessing default interface methods and requires the workaround I shared [here](https://github.com/datafaker-net/datafaker/issues/790#issuecomment-1527033973).  CF2021 (and possibly CF2018) appear to access the methods, but don't identify the interface methods when dumping the base object. Adobe rarely fixes any bugs that I report in supported versions of ColdFusion. (Issues that I report are often fixed in upcoming commercial versions rather than currently supported versions.)  I try to write cross-compatible CFML that works on both Adobe (commercial) & Lucee (open-source) platforms and have tried to support CF2016, but sometimes that's not always possible.

NOTE: Even though CF2021 can output `faker.name().fullName()`, the base "name" method is not displayed when "faker" is dumped. The `name()` methods are displayed when `name()` is dumped, but I'd have to read online documentation or manually navigate the JAR file to know which providers are available.

For use w/ColdFusion 2016, I've downloaded a pre-compiled datafaker 1.5.0 JAR file from [MvnRepository](https://mvnrepository.com/artifact/net.datafaker/datafaker/1.5.0) and it works as expected and displays the 165 provider methods.

I removed the previously mentioned dependencies (snakeyaml & Generex) as the `datafaker-1.x.0.jar` library appears to work fine without them so far.

**Comment by kingthorin** [comment]
This seems to be a ColdFusion issue not a datafaker issue.

**Comment by JamoCA** [comment]
Possibly...  I'm not sure what best practices are when it comes to Java, but most major third-party java libraries that I've used just work and fully self-document themselves when the main object is dumped. This wasn't the case with DataFaker and I thought that it was a bug.  DataFaker 1.7.0+ is just written differently and requires some extra work & knowledge for use with ColdFusion.

**Comment by bodiam** [comment]
> I removed the previously mentioned dependencies (snakeyaml & Generex) as the `datafaker-1.x.0.jar` library appears to work fine without them so far.

Unlikely. We use SnakeYAML to read all the data, and we use Generex to  generate strings based on regular expressions, which can be triggered programmatically but also from YAML files. Not having Generex might work as long as you don't encounter regular expressions, but DataFaker will be very limited without YAML. Possibly your system already has SnakeYAML? It's a quite common library.

**Comment by bodiam** [comment]
Ps: would you be willing to document this as part of our documentation? I don't think we have a huge amount of CFML users, but a small topic in the documentation on how to get this to work might benefit future CFML users.

**Comment by snuyanzin** [comment]
should we close since it should be fixed on CFML side and nothing could be done on datafaker side?
