### ISSUE TITLE
Create positive / negative number support

### ISSUE THREAD

**Issue by bodiam** [datafaker-net/datafaker#81]
For one of the projects I'm working on, I need a random positive, and a random negative number. I can use the random (min, max) option, but that's less expressive than just saying "positive()"

**Comment by Lance-Azrael** [comment]
We will happy to learn this project and finish this issue! :)
---- SE_SUSTech, group: Lanrand

**Comment by bodiam** [comment]
This has been fixed here: https://github.com/datafaker-net/datafaker/commit/a5282bfb3834ebc8c88e18b913b34ecf4fad03f9
