### ISSUE TITLE
Specify locale when using Java Object transformer

### ISSUE THREAD

**Issue by panilya** [datafaker-net/datafaker#822]
I do not quite understand why the `populate` method in BaseFaker is static. Since the `populate` method is static, I can't specify the locale of the Faker. 

I have a predefined schema and I use the `@FakeForSchema` annotation. My schema has a phone number and I want to specify the locale of that phone number. How to do this?

**Comment by snuyanzin** [comment]
you should do it within your schema definition.
The reason is that you can not satisfy per field specification with declaring it on e.g.`populate` method level

**Comment by panilya** [comment]
My mistake, sorry, didn't notice in the documentation
