### ISSUE TITLE
POSIX character classes support

### ISSUE THREAD

**Issue by wazzeps** [datafaker-net/datafaker#831]
**Is your feature request related to a problem? Please describe.**

Currenty I'm trying to generate mixed data using regexify:

Faker faker = new Faker();
faker.regexify("[a-zA-Z0-9!@#$%^&*()]{50}");

as a result I'm getting a string with about 50% of special symbols.
Although I'm expecting a uniform distribution across character groups.

I assume that each special character counts as one group, the same as a-zA-Z or 0-9.

**Describe the solution you'd like**

Add supporting of POSIX character classes allowing \p{Punct} to be used.

**Comment by snuyanzin** [comment]
Have you tried `Text` provider where you could custom your group and set minimum number of occurences in result?
e.g.
```java
   public static final String EN_LOWERCASE = "abcdefghijklmnopqrstuvwxyz";
   public static final String EN_UPPERCASE = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
   public static final String DIGITS = "0123456789";
   ...
   final Text.TextRuleConfig config = Text.TextSymbolsBuilder.builder()
        .len(faker.number().numberBetween(6, 10))
        .with(EN_LOWERCASE, 1)
        .with(EN_UPPERCASE, 1)
        .with(DIGITS, 1).build();
   String text = faker.text().text(config);
```

**Comment by wazzeps** [comment]
It's suitable. Thanks!
