### ISSUE TITLE
faker.internet().url() creates the hostname only without the scheme

### ISSUE THREAD

**Issue by BeniaminK** [datafaker-net/datafaker#840]
**Describe the bug**
faker.internet().url() creates the hostname only without the scheme

**To Reproduce**
```
faker.internet().url()
```
return `www.sherita-mcglynn.io`

**Expected behavior**
```
faker.internet().url()
```
return `https://www.sherita-mcglynn.io`

**Versions:**
 - OS: any
 - JDK 19
 - Faker Version: 1.9.0

**Additional context**
No context - I think there should be a method that crates the real URL, not just a hostname

**Comment by kingthorin** [comment]
Agreed, seems reasonable to me.

**Comment by bodiam** [comment]
It's a bit of a breaking change, but I think you're right too. Maybe we can keep the behaviour of the old method by renaming it, and create a new one which takes the http method into account. Should we only create https schemes, or should we take into account other schemes? (we have a method for random schemes too).

Also, we could consider adding a `uri` method next to the `url` method perhaps?

**Comment by kingthorin** [comment]
PR coming.
