### ISSUE TITLE
Tyre sizes

### ISSUE THREAD

**Issue by jaapcoomans** [datafaker-net/datafaker#862]
**Is your feature request related to a problem? Please describe.**
For my current project we work with tyre sizes for cars. Currently we use a combination of the number data provider and regexify. A tyre size fake data provider would relief us of having to 

**Describe the solution you'd like**
Either a dedicated tyre fake data provider, or one or more tyre size methods in the Vehicle provider.

**Describe alternatives you've considered**
Rolling our own by using lower level fake data providers and combining their results.

**Additional context**
I'm happy to file a PR for this as well. But before I start on that I thought it would be good to get some feedback first.
I'm a little bit in doubt if this should be a separate tyre fake data provider, or if it should be part of the already existing Vehicle fake data provider.

**Comment by snuyanzin** [comment]
There ar 2 ways: 
1. custom provider. It's possible to create and use custom provider in a way you like (no need to merge it to datafaker, while e.g. for JavaFaker it is the only way to go) more about custom providers at https://www.datafaker.net/documentation/custom-providers/
2. new provider to datafker, then it should be more or less generic that other users could also potentially use it

**Comment by kingthorin** [comment]
Huh, today I learned:

> Tire and tyre both mean a covering for a wheel, usually made of rubber. Tire is the preferred spelling in the U.S. and Canada. Tyre is preferred in most varieties of English outside North America.

@jaapcoomans could you provide a sample of the values you’re currently generating?

**Comment by bodiam** [comment]
Sounds silly, but I don't really know if we use British or US English. We have `zipCode`, but we also have `postcode`. I think I'm personally more of US English fan. `tire` seems to have a few more hits on google (1.3billion vs 260m).

**Comment by jaapcoomans** [comment]
@bodiam We had a great meetup yesterday indeed 😄 . @eliasnogueira inspired some more people to take a look at datafaker.

**Comment by kingthorin** [comment]
@jaapcoomans thanks for the details, do it!

**Comment by bodiam** [comment]
Thanks for providing the details, I think adding it to Vehicle would make sense

**Comment by bodiam** [comment]
Hi @jaapcoomans , closing this issue for now.

**Comment by kingthorin** [comment]
I’m gonna re-open this. I’ll tackle it after vacation 😉

**Comment by kingthorin** [comment]
https://www.wheel-size.com/tire/
