### ISSUE TITLE
Custom provider not recognized in expression

### ISSUE THREAD

**Issue by ako** [datafaker-net/datafaker#866]
The following might not be a bug in your code, but it is at least indicative of missing documentation....

Goal is to enable my users to generate fake csv files with 100s of records for import into database tables using the expressions, so no need to do custom java coding for csv generation. The tables expect unique id values to identify the records. 

I've created a custom sequence number provider that i want to use in an expression, but the provider is not resolved when used in an expression.

The custom provider works, as the following java code gives the expected output:

       SequenceNumberFaker sequenceNumber = new SequenceNumberFaker();
        System.out.println(sequenceNumber.sequenceNumber().next("EmpId"));
        System.out.println(sequenceNumber.sequenceNumber().next("DeptId"));
        System.out.println(sequenceNumber.sequenceNumber().next("EmpId"));
        System.out.println(sequenceNumber.sequenceNumber().next("EmpId"));
        System.out.println(sequenceNumber.sequenceNumber().next("DeptId"));

shows:

    1
    1
    2
    3
    2

The following expression throws a provider not resolved exception:

        Faker faker = new Faker();
        String data = faker.expression("#{csv ';','\"','true','10','EmployeeId','#{SequenceNumber.next ''empId''}','Firstname','#{Name.first_name}','Lastname','#{Name.last_name}'}");

Result:

    Exception in thread "main" java.lang.RuntimeException: Unable to resolve #{SequenceNumber.next 'empId'} directive for FakerContext   FakerContext{, locale=net.datafaker.internal.helper.SingletonLocale@bb16a58a, randomService=net.datafaker.service.RandomService@4678c730}.
	at net.datafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:572)
	at net.datafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:574)
	at net.datafaker.service.FakeValuesService.expression(FakeValuesService.java:448)
	at net.datafaker.providers.base.BaseFaker.expression(BaseFaker.java:467)
	at tests.impl.TestMain.main(TestMain.java:30)

Haven't found a unit test that illustrates this use case. What am i doing wrong here?

**Comment by kingthorin** [comment]
`EmployeeId','#{SequenceNumber.next ‘`

Shouldn’t that be lower `s` and no trailing space?

**Comment by kingthorin** [comment]
🤷‍♂️ I could be totally wrong, I haven’t used this part of the lib yet.

**Comment by bodiam** [comment]
Hi @ako , I think you're using the wrong faker. In your example, you are using `Faker`, but you should register the custom Provider at your own Faker. If you then do:

```
        BugFaker faker = new BugFaker();
        String data = faker.expression("#{csv ';','\"','true','10','EmployeeId','#{Insect.nextInsectName}','Firstname','#{Name.first_name}','Lastname','#{Name.last_name}'}");
        System.out.println(data);
```

This seems to work. You can find the code I've used to reproduce it here:

https://github.com/datafaker-net/datafaker/tree/custom_csv_provider/src/test/java/net/datafaker/providers/base/bug
(sorry, it's a bit sloppy, but I hope it's clear enough)

**Comment by bodiam** [comment]
> Shouldn’t that be lower `s` and no trailing space?

He's passing an argument to the `next` method.

**Comment by snuyanzin** [comment]
@ako 
regarding 
>Goal is to enable my users to generate fake csv files with 100s of records for import into database tables using the expressions, so no need to do custom java coding for csv generation. The tables expect unique id values to identify the records.

have you looked at https://github.com/datafaker-net/datafaker-gen which could do what you've described without coding (only conf files)

**Comment by ako** [comment]
@bodiam Thanks, your suggestion to instantiate the sequence number Faker works, but i wonder how this is supposed to work if you have multiple custom providers?

**Comment by snuyanzin** [comment]
in case of multiple custom provider you can register all under custom faker 
e.g.
```java
public class BugFaker extends Faker {
    public BugProvider insect() {
        return getProvider(BugProvider.class, BugProvider::new, this);
    }
}
```

there will be more than just one `insect` method.

**Comment by bodiam** [comment]
> how this is supposed to work if you have multiple custom providers?

The BugFaker is the entry point for all the custom generations. It should be called MyCompanyCustomFaker or so, where you can register a provider for Insects, Sequence Numbers, Tire sizes, etc, and in your code, instead of using Faker, you use your own subclass everywhere.

**Comment by bodiam** [comment]
Hi @ako , I assume this issue is addressed, but feel free to reopen if it's not.
