### ISSUE TITLE
The same value is returned for random expressions within single run

### ISSUE THREAD

**Issue by valfirst** [datafaker-net/datafaker#87]
**Describe the bug**
The same value is returned for random expressions within single run

**To Reproduce**
```java
import net.datafaker.Faker;

public class Main
{
    public static void main(String[] args)
    {
        Faker faker = new Faker();

        System.out.println(faker.expression("#{regexify '[a-z]{5}[A-Z]{5}'}"));
        System.out.println(faker.expression("#{regexify '[a-z]{5}[A-Z]{5}'}"));
        System.out.println(faker.expression("#{Address.city}"));
        System.out.println(faker.expression("#{Address.city}"));
    }
}
```

Actual result:
```
brmbnQKCAJ
brmbnQKCAJ
Port Quinn
Port Quinn
```

**Expected behavior**
Random data should be generated for each expression invocation.

**Versions:**
 - Faker Version: `1.2.0`

**Additional context**
This is a regression issue. It's not reproduced for faker `1.1.0`

**Comment by bodiam** [comment]
I think this issue got auto closed, sorry for that. Could you verify if the fix works using the snapshot version?

**Comment by valfirst** [comment]
Verified: the issue is fixed. Thank you!

**Comment by bodiam** [comment]
@valfirst  thanks for reporting it! I'll release an official version in a few days.

**Comment by nineinchnick** [comment]
Looking forward to that release as Datafaker is the base for a connector I recently created to generate random data in SQL: https://github.com/nineinchnick/trino-faker/

**Comment by bodiam** [comment]
This week, promise!
