### ISSUE TITLE
Memory leak in PROVIDERS_MAP

### ISSUE THREAD

**Issue by lukelast** [datafaker-net/datafaker#883]
**Describe the bug**
Each instance of `Faker()` created will permanently consume memory. If you create enough instances you'll OOM.

**To Reproduce**
Code to reproduce is here:
https://github.com/lukelast/datafaker-bug-repro/blob/main/src/main/kotlin/Main.kt

The summary of the code is to create a lot of instances, let them be GC'd, then check heap usage.

**Expected behavior**
I expect heap usage to go back to the original size as everything is GC'd away.

**Versions:**
 - OS: Windows, Linux
 - JDK: 17, 20
 - Faker Version: 2.0.1

**Additional context**
![image](https://github.com/datafaker-net/datafaker/assets/1649361/7545fbbb-451a-453b-804c-f1a456ed3458)
![MicrosoftTeams-image](https://github.com/datafaker-net/datafaker/assets/1649361/5cfb55f1-7dcb-413f-80e5-2751033e4d61)

**Comment by snuyanzin** [comment]
thanks for reporting
the problem waws in absence of hashcode/equals
there is a fix available for that
