### ISSUE TITLE
Random generator from java Enums

### ISSUE THREAD

**Issue by vadeg** [datafaker-net/datafaker#888]
**Is your feature request related to a problem? Please describe.**

I am often need to create test data using random values from a specific `enum`.

**Describe the solution you'd like**
Extend `RandomService` with a function which can return random `enum` value from a provided enum

**Describe alternatives you've considered**
Write generator for every project

**Additional context**
-

**Comment by snuyanzin** [comment]
Did you have a look at `Options.option`?

**Comment by bodiam** [comment]
We already have supprt for this in the Option class, didn't that work for you?

**Comment by vadeg** [comment]
Yes. It is hard to find it. Closing the ticket. Thank for your response.

**Comment by snuyanzin** [comment]
yes, sometimes documentation is weird
you can contribute to documentation by the way to make it more clear

**Comment by bodiam** [comment]
An overview of the basic data generators (strings, ints, lists, enums, etc) night be very handy if this is missing from the documentation, and contributions would be very welcome.

**Comment by kingthorin** [comment]
I’m re-opening this one to review/tackle docs after vacation too 😉

**Comment by kingthorin** [comment]
I’m thinking this https://github.com/datafaker-net/datafaker/blob/main/docs/documentation/schemas.md#java-object-transformation is a good place to add some content on Enums and Options.option. Sound good?

**Comment by bodiam** [comment]
Hmm, I don't think Enums have much overlap with the schema part, I think it would be more easily findable at the basic usage section, since all you have to do is do faker.options().option(Enum.class)?

**Comment by kingthorin** [comment]
Okay. Thanks.
