### ISSUE TITLE
Question  or Feature : JPA objects to Schema Object

### ISSUE THREAD

**Issue by gogo-boot** [datafaker-net/datafaker#892]
Hi, 

I like to generate a `Schema` object from JPA objects. is there an example or is there a feature?
I don't find a example or feature. I might try if I can generate the Schema object according to JPA models.

my current usecase is, 

when the Project change Database-Schema, developers will change the JPA models according to Database. 
It this case, the datafaker-Schema object stays stale and might not fit to generate SQLs and get error by inserting queries. I like to automate this, so I don't have to change Schema object everytime when JPA models changes.

**Comment by snuyanzin** [comment]
that's an interesting usecase
currently there is no such feature
your contribution would be welcome
