### ISSUE TITLE
[BUG]: ID_NUMBER flaky call of the method valid()

### ISSUE THREAD

**Issue by y-lazakovich** [datafaker-net/datafaker#897]
**Describe the bug**
ID_NUMBER provider contains bug with calling the method `valid()`
sometimes it returns exception, 
as final user I expect that calling this method should NOT throwing me the Exception about it

**To Reproduce**
Try to increase count of repeatable from `100` to `20000`
And call several times:
As results you should see
<img width="1375" alt="image" src="https://github.com/datafaker-net/datafaker/assets/25825892/be42a538-c504-4208-8093-a6fc0bde0413">

[Code to reproduce
](https://github.com/datafaker-net/datafaker/blob/main/src/test/java/net/datafaker/idnumbers/EnZAIdNumberTest.java#L29)

**Expected behavior**
Returns     `valid id_number value`

**Actual behavior**
Can return `flaky id_number value` 

**Versions:**
 - OS: `MacOS` `Linux` `Windows`
 - JDK: `corretto 17`
 - Faker: `1.9.0`

**Comment by y-lazakovich** [comment]
Thanks for quick reply

Will try to update our project than will return with the feedback about this issue

**Comment by bodiam** [comment]
@y-lazakovich I'm closing this issue for now. Please let us know if this issue still occurs.
