### ISSUE TITLE
[discussion] Move username to internet?

### ISSUE THREAD

**Issue by bodiam** [datafaker-net/datafaker#901]
Hi, 

just a call for input: at the moment, we have a Name class which deals with first names, last names, middle names, etc.

However, it also deals with usernames, and it feels a bit out of place there. I'm thinking of moving it to Internet, where I think it's slightly better suited, but this will break the API.

Suggestions / feedback?

**Comment by bodiam** [comment]
I don't completely follow semver, otherwise Datafaker would be at version 10 by now. I do agree with the removal . deprecation part, but I would probably remove it in Datafaker 2.2.x or so.

**Comment by kingthorin** [comment]
That’s fine, as long as we give library users a chance to adapt I think.

**Comment by snuyanzin** [comment]
i think 1 version with deprecated and them remove is ok
