### ISSUE TITLE
Kotlin example for JavaObjectTransformer does not work

### ISSUE THREAD

**Issue by zoobert** [datafaker-net/datafaker#918]
**Describe the bug**
Using the example code provided in the [Java Object transformation](https://www.datafaker.net/documentation/schemas/#yaml-transformation) for Kotlin produces a `NoSuchMethodException`.

**To Reproduce**
1. Copy the Kotlin from the section for both the `Person` data class and the transformation
2. Run the test 
3. Boom!

**Expected behavior**
A successful run using the code copied from the documentation.

**Versions:**
 - OS: OSX
 - JDK 19
 - Faker Version 2.0.1

**Additional context**
This appears to be an incompatibility between how Java objects are constructed and what is available for a Kotlin data class. The call to `getDeclaredConstructor()` does not succeed, so a new instance is not created. I don't know how this would work for a Kotlin data class where I believe it has a single constructor where the values are required. Converting this to a non-data class or one of the methods suggested in [this](https://www.baeldung.com/kotlin/instantiate-data-class-empty-constructor) article seems to work. However, the code in the documentation as is, does not work. 

```
java.lang.RuntimeException: java.lang.NoSuchMethodException: com.modios.taxsolution.calc.kafka.Person.<init>()
	at net.datafaker.transformations.JavaObjectTransformer.apply(JavaObjectTransformer.java:69)
...
Caused by: java.lang.NoSuchMethodException: com.modios.taxsolution.calc.kafka.Person.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3641)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2810)
	at net.datafaker.transformations.JavaObjectTransformer.apply(JavaObjectTransformer.java:65)
```

**Comment by snuyanzin** [comment]
Could you please share the code snippet to reproduce the issue with aformentioned `com.modios.taxsolution.calc.kafka.Person`?

**Comment by zoobert** [comment]
Sure. It looks exactly like the one from the tutorial:

```
    data class Person(
        var firstName: String,
        var lastName: String,
        var birthDate: Date,
        var id: Int
    )
```

I did not extract the problem into its own repository since it was basically what was in the tutorial. I'm using Kotlin 1.8 and targeting Java 1.19.

**Comment by bodiam** [comment]
Hi @zoobert , thanks for reporting this. Could you give the latest milestone a try (2.0.2-SNAPSHOT)? I've just implemented a fix for this.

**Comment by bodiam** [comment]
Hi @zoobert , I think this issue is resolved, if it's not, feel free to make another issue.
