### ISSUE TITLE
Wrong country is generated for the given Locale

### ISSUE THREAD

**Issue by talhakabakus** [datafaker-net/datafaker#948]
**Describe the bug**
As the title is self-explanatory, the country of the generated address for the given locale, which is Turkish for my case, is not valid. I got different values, including but not limited to `"United States of America"`, `"Russia"`, `"Holland"`,  `"Belgium"`, etc.

**To Reproduce**
```
Locale localeTR = new Locale("tr", "TR");
Faker faker = new Faker(localeTR);

Address adres = faker.address();
String country = adres.country(); // should be "Türkiye"
```

**Expected behavior**
The `country` method should return the String `"Türkiye"`.

**Versions:**
 - OS: macOS Ventura 13.5.1
 - JDK: 18.0.2
 - Faker Version: 2.0.1

**Comment by snuyanzin** [comment]
Could you please explain why do you think it should be '`Türkiye`?
It returns any from available in a language derived from locale. 
There is nowhere stated in design that it should return country/address based on locale.

Also it is not clear if you 100% know the country you need why are you going to generate it in a random instead of using a constant value?

**Comment by talhakabakus** [comment]
Hi @snuyanzin ,

Thanks for your care, much appreciated.

Let me explain you: The Faker object was generated with a given locale. So, I expect the generated values in the given locale, which do work for many cases (phone number, name, etc.) apart from the country. The city information of the generated address is valid, a city in Türkiye; but the country is not. For example, I get an address like this: Eminonu, Istanbul, Belgium, which does not make sense.

Hope this makes clear.

**Comment by snuyanzin** [comment]
data for generation for `tr` locale are taken from https://github.com/datafaker-net/datafaker/blob/55f36a97bc0c4f38680f56006b7c4b4812e79e5c/src/main/resources/tr.yml#L32-L36
so it looks expected.

You can create and register your own data provider which could return only Turkey or any other country you need related data. How to do it is described at https://www.datafaker.net/documentation/custom-providers/

**Comment by bodiam** [comment]
Also, if you want to add more (all?) the countries to tr.yml in the Turkish language, that would be very appreciated and we would certainly welcome such a contribution.

**Comment by bodiam** [comment]
Not an issue, so closing. However, extra data is always appreciated, so a PR would be welcome.
