### ISSUE TITLE
Request for next release

### ISSUE THREAD

**Issue by y-lazakovich** [datafaker-net/datafaker#957]
**Is your feature request related to a problem? Please describe.**
At the moment the last version is `Faker 2.0.1`
This version and previous contain issue with Memory leak which were fixed in next snapshot version with https://github.com/datafaker-net/datafaker/issues/883

**Describe the solution you'd like**
Our team want to use in project release version
Or only one way to download last snapshot to our artifactory repository and use it - but we think it is not the best practise

**Comment by bodiam** [comment]
I'm currently away on holiday with no access to release a new version, so best I can do is release a new version in approx 3 weeks. You can use the snapshot version in the meantime, it's very stable, I don't think we had many issues with that in the past.

**Comment by bodiam** [comment]
2.0.2 has been released.
