### ISSUE TITLE
Faker v2.0.2 generates invalid Sweden SSN

### ISSUE THREAD

**Issue by ksiczek** [datafaker-net/datafaker#986]
Hi there 👋 

We've been using `net.datafaker.providers.base.IdNumber#validSvSeSsn` for quite some time but it stopped working with the `2.0.2` version. Our application resolves users' birth date from their Swedish SSN which, according to the SSN _specification_ should be always possible. Unfortunately, the faker started returning random numbers, for example, `295659+4036`. Can you refer to that? The method `validSvSeSsn` suggests that the number would follow the rules so maybe there is a regression bug in the `2.0.2`?

**Comment by bodiam** [comment]
Thanks for reporting this, we will fix this ASAP.

@snuyanzin  could it be that this one introduced a regression: https://github.com/datafaker-net/datafaker/pull/927/files

**Comment by snuyanzin** [comment]
Seems we are in a lack of tests for such cases
@ksiczek could you please check if https://github.com/datafaker-net/datafaker/pull/987 works ok for your case?

**Comment by bodiam** [comment]
I've just merged the PR, if you could try the snapshot version, that would be great, happy to make a release this weekend if it fixes the problem.

**Comment by ksiczek** [comment]
Cool, thanks for such a prompt reaction. I've checked and it seems it works for us or at least it is not as bad as before ☺️  Just bear in mind that our test suites use this method here and there.

As far as I can tell you only generate the number in the format '######[-|+]#### which means that it is for people born in 19XX, right? If so, then the number `631221+6481` seems valid but 🇸🇪 people get `+` when they turn 100 years old so the number is actually invalid, isn't it? Regarding your implementation - do you repeatedly create a pattern-matching number until you find something valid, aren't you? 

I think the change is worth releasing anyway 👍

**Comment by bodiam** [comment]
Hmm, I'm not sure if we published a new version of the snapshot. It seems the builds are failing.

**Comment by ksiczek** [comment]
I haven't seen `2.0.3-SNAPSHOT` so I checked the project out and installed it in the local repository - that is how I checked your fix.

Regarding the logic we used 
- [Wikipedia description](https://en.wikipedia.org/wiki/Personal_identity_number_(Sweden))
- [Other SE resources](https://www.skatteverket.se/servicelankar/otherlanguages/inenglish/individualsandemployees/livinginsweden/personalidentitynumberandcoordinationnumber.4.2cf1b5cd163796a5c8b4295.html)
- Our colleagues in 🇸🇪 😄 

It seems that the number itself consists of:
1. A date which might be `yyyyMMdd` or `yyMMdd`
2. A `-` or `+` separator
3. A suffix that contains sex, checksum, etc.

So my interpretation would be that if you have `120923[-|+]####` then the person was born either in 1912 or 2012 and yes, according to the docs:

> Between the birthdate and the birth number is a hyphen (-), which is replaced by a plus sign (+) in the year the person becomes 100 years old.

We work for 🇸🇪 customers and I'll have a look on Monday if we could support you by means of a PR. Is that OK with you?

**Comment by kingthorin** [comment]
Sounds great to me.

**Comment by bodiam** [comment]
Absolutely, a PR would be more than welcome, happy to make a release which includes your fix!

**Comment by bodiam** [comment]
I'm assuming this is no longer an important issue, so I'll close the ticket for now. If one day in the future you want to send a PR, it would be most welcome.
