### ISSUE TITLE
Being able to differentiate masculine and feminine names

### ISSUE THREAD

**Issue by selbiselbi** [datafaker-net/datafaker#999]
Currently, when generating first names, the generator does not differentiate between male and female names (I'm thinking about french names, but I guess it's applicable to every country). Do you think it would be possible to implement this feature? 

I could try to implement this (not sure how though for the moment).

**Comment by selbiselbi** [comment]
Yeah I think those are questions that should be asked indeed. I might go with a custom solution in my code, not necessarily in this library. 

It'll always be too difficult I think for people to agree to such things, and I may have rushed a bit on this subject.

Also, this lib is about generating random (real-looking) datas, not precises one. So I think my proposition is answered already.

**Comment by bodiam** [comment]
I thought that some locales already have the concept of male and female names. I'm not sure we expose it as a property, but I wouldn't mind a PR which does this.

**Comment by bodiam** [comment]
@selbiselbi I've implemented this change, if you can try out 2.0.3-SNAPSHOT, that would be great.
